### ISSUE TITLE
this function doesn't call back listener

### ISSUE THREAD

**Issue by waixiaoyu** [apache/jena#1231]
https://github.com/apache/jena/blob/1ccac6bf29ac69d859e2ee50469598193f8c181c/jena-core/src/main/java/org/apache/jena/graph/GraphUtil.java#L309

if I register a WatchStatementListener in this model, when call above function to remove a sub-graph, the listener will not work

**Comment by waixiaoyu** [comment]
move to jira

**Comment by afs** [comment]
Here is fine. Or JIRA. Whichever works best.

WatchStatementListener is in Jena test code, but it should work.

Do you have an example of usage because `deleteFrom` executes differently base on the relative sizes of `dstGraph` and `srcGraph`.
