### ISSUE TITLE
Add support for authentication with a bearer token

### ISSUE THREAD

**Issue by Aklakan** [apache/jena#1292]
A quick request to make the following single method public so that I can inject a bearer token - if possible for 4.5.0-SNAPSHOT. On the main branch I already get 4.6.0-SNAPSHOT - so I am not sure if PRs for 4.5.0 are still possible.

Because of the lack of interceptors in java HttpClient (I am underwhelmed...) this seems to be the only reliable way to make bearer token auth working with jena. De-facto, this AuthEnv is a kind of interceptor framework after all...
Of course adding a bearer token helper method to AuthLib would also be nice, but from my side this can happen in 4.6.0 if I can register my own auth mod for now.

```
public class AuthEnv {
    void registerAuthModifier(String requestTarget, AuthRequestModifier authModifier) {
        // Without query string or fragment.
        String serviceEndpoint = HttpLib.endpoint(requestTarget);
        //AuthEnv.LOG.info("Setup authentication for "+serviceEndpoint);
        authModifiers.put(serviceEndpoint, authModifier);
    }
}
```

**Comment by afs** [comment]
Does `HttpLib.modifyByService` work for you? It can add the header.
https://jena.apache.org/documentation/sparql-apis/#customization-of-http-requests


4.5.0 has been built and is currently awaiting the VOTE from the PMC.
The build uses the Apache release configuration of the maven release plugin. If the version moves on,

**Comment by Aklakan** [comment]
Hi Andy, thanks alot - the snippet below works:
```java
   String bearerToken = "SECRET";
   HttpRequestModifier modifier = (params, headers) -> {
       headers.put("Authorization", "Bearer " + bearerToken);
   };
   RegistryRequestModifier.get().add(url, modifier);
```

However, there is a minor follow up issue:
If the bearer token times out, then first a message is logged such as:
```
Bearer error="invalid_token", error_description="An error occurred while attempting to decode the Jwt: Jwt expired at 2022-05-03T20:22:50Z", error_uri="https://tools.ietf.org/html/rfc6750#section-3.1"
```

but then it causes a non-ideal NPE in AuthLib.authenticateHeader:

```java
public class AuthLib {
    private static AuthChallenge authenticateHeader(HttpResponse<?> httpResponse) {
        List<String> headers = httpResponse.headers().allValues("WWW-Authenticate");
        if ( headers.size() == 0 )
            return null;
        // Choose first digest or first basic.
        AuthChallenge aHeader = null;
        String result = null;
        for ( String headerValue : headers ) {
            AuthChallenge aHeader2 = AuthChallenge.parse(headerValue);
            if ( aHeader2 == null )
                AuthEnv.LOG.warn("Bad authentication response - ignored: "+headerValue);
            // Prefer Digest
            switch(aHeader2.authScheme) { // BUG: If aHeader2 is null we get both a log message but here it raises an NPE
                case  DIGEST :
                    return aHeader2;
                case BASIC:
...

**Comment by afs** [comment]
That would have happened if an `AuthModifier` were used.

It needs `AuthScheme` extending and `AuthChallenge.parse` etc changing. Then there needs to be a recovery or more likely, passing on up the 401.

What else needs to accommodate that?

**Comment by afs** [comment]
Some context so we can build or simulate  test cases:
* What software system are you calling?
* What `WWW-Authentication` header do you get back?

**Comment by Aklakan** [comment]
The software is a commercial product from @eccenca called [corporate memory](https://eccenca.com/products/enterprise-knowledge-graph-platform-corporate-memory) which is a knowledge graph platform - which means it combines sparql enpdoint, workflow engine, interlinking, vocabulary management, user management, etc + user interfaces. It also uses Apache Jena in the backend.

So far I haven't used auth much, therefore I am not very familiar with the issues that arise with latest Jena and how to best address them - but maybe @seebi and his team (from eccenca) have already done some deeper investigation with tasks/issues on their backlog.

`curl -I` on the currently private instance yields:
```
HTTP/2 401 
server: nginx/1.21.6
date: Tue, 03 May 2022 21:32:52 GMT
vary: Origin,Access-Control-Request-Method,Access-Control-Request-Headers
www-authenticate: Bearer
```

**Comment by seebi** [comment]
HI together, this is [our architecture](https://documentation.eccenca.com/latest/deploy-and-configure/system-architecture).

The sparql endpoint is a resource server in an oauth2 zone used together with keycloak.

You could do something similar e.g. with [oauth2 proxy](https://github.com/oauth2-proxy/oauth2-proxy) ...

**Comment by afs** [comment]
Could you test for other things that might be needed by avoiding the NPE so the system returns without NPE?

It really would be helpful to get all the points enumerated where "bearer" matters and not deal with them one by one.

**Comment by Aklakan** [comment]
I've been working with oauth in the past days and IMHO just handling `Authorization: Bearer` should be enough.

I managed to use spring security to authenticate with my local test app that I registered with my gitlab account .

Because obtaining the bearer token is 'app-driven' I'd say its an application's concern to pass on the bearer token to components such as Jena remote sparql requests. It may make sense having a global callback registry in Jena for getting notified about failed authentications so that an application can then take action, such as redirecting the user to repeat the auth process.

**Comment by afs** [comment]
The application sees a failed authentication as an exception 401.

Fixes and improvements in #1301. HTTP authentication is a bit squirly because of legacy cases.

Adding challenge handling for bearer auth is probably doable but it's yet another step. Rather than delay everything PR #1301 at least fixes the original problems and should work when the bearer token is added - failure is a 401 exception.

One case is that the token is being passed along a path service requests and code in the 401 handler may find it hard to give transparent. PR #1301 at least fixes the original problems and should work when the bearer token is added.

@seebi -- I'm guessing that in your architecture, the token is added before the original request and not based on a HTTP challenge. Is that correct?

Testing the PR would be great - this is quite sensitive to the execution environment (and my reading of the RFCs!).

**Comment by seebi** [comment]
> @seebi -- I'm guessing that in your architecture, the token is added before the original request and not based on a HTTP challenge. Is that correct?

correct, the token is fetched from a different component (e.g. [keycloak](https://www.keycloak.org/)) and then added to all requests.

**Comment by seebi** [comment]
@Aklakan Do you need help in testing this?

**Comment by afs** [comment]
The current PR needs the bearer token provided. 

@seebi sounds like our setup - we don't involve 401, the token is known to be needed and is always added.

**Comment by seebi** [comment]
mhmm .. In our case requests without a token return a 401

```
∴ curl -H "Authorization: Bearer $(cmemc admin token)" "$(cmemc config get DP_API_ENDPOINT)/proxy/default/sparql"
{"title":"Bad Request","status":400,"detail":"Required request parameter 'query' for method parameter type String is not present"}

∴ curl  "$(cmemc config get DP_API_ENDPOINT)/proxy/default/sparql"
{"title":"Unauthorized","status":401,"detail":"Full authentication is required to access this resource"}
```

**Comment by afs** [comment]
#1335 provides code to handle a 401 challenge for bearer tokens. It calls back into the application to get a token.

**Comment by Aklakan** [comment]
So I can confirm that the solution from more than an hour ago seems satisfactory to me - using an invalid token or none at all resulted in 401 rather than NPE:
```
Caused by: org.apache.jena.atlas.web.HttpException: 401 - Unauthorized
	at org.apache.jena.http.HttpLib.exception(HttpLib.java:231)
	at org.apache.jena.http.HttpLib.handleHttpStatusCode(HttpLib.java:161)
```
Andy just added a new PR like 30min ago which I haven't tried yet.

**Comment by afs** [comment]
Thanks.

The addition forced pushes are just some cleanup.

I also have a test setup outside the jena test suite with a Fuseki + a test BearerAuth fuseki module that executes requests with both ahead of time registration of a token and in in response to a 401 challenge.

Almost everything to do with bearer auth involves application supplied code to access the deployment environment.
