### ISSUE TITLE
Performance issue with text/csv and HTTP compression

### ISSUE THREAD

**Issue by SimonBin** [apache/jena#1295]
I'm investigating a performance degradation that seems to happen only in combination with HTTP compression and text/csv.

I'm opening this issue here first without a complete demo, in case anyone has an idea where to look.

I am running a request to fuseki like this:

```
curl http://fuseki/sparql -H 'Accept: text/csv' -d 'query=select *{?s ?p ?o.}limit 100000' | wc -l
100001
```

if I only add the `-H 'Accept-Encoding: gzip' ` header, like browsers will do, the same query:
```
curl http://fuseki/sparql -H 'Accept: text/csv' -H 'Accept-Encoding: gzip' -d 'query=select *{?s ?p ?o.}limit 100000' | zcat | wc -l
100001
```

it takes 22 times as long!

Interestingly though, the other result formats (json, tsv) work fast both with and without the Accept-Encoding

**Comment by afs** [comment]
Hi @SimonBin A few details would help.

- Which versions of Fuseki have you tried? 
- What are the times you are seeing? The same if you call twice, one after another?
- Is there an intermediary (e.g reverse proxy) on the HTTP path?

**Comment by SimonBin** [comment]
Hi @afs thank you for the prompt response

- Fuseki 4.5.0-SNAPSHOT 7be194cdaf8c1b9bffd8ef20192015f0f0348bd4
- times stay the same (3 seconds vs. 1 minute)
- no intermediary
- sample dataset with random triples was enough to trigger it:
  ```
   { echo '@prefix : <http://example.com/> .
     _:r0 :has [ :label "1" ]'
     for i in $(seq 2 2500000); do
       echo ", [ :label \"$i\" ]"
     done
     echo . } > demo.ttl
   ```

however, while trying to reproduce it, I found that it 4.5.0 release! so case closed I guess?? still, a very curious issue

**Comment by afs** [comment]
There was a Jetty upgrade 10.0.8 -> 10.0.9. That's the only change that looks even remotely in the area.

https://github.com/eclipse/jetty.project/issues/7567

touches gzipping. But not in a way that clearly applies to this case.
