### ISSUE TITLE
Potential IllegalArgumentException in RefEval

### ISSUE THREAD

**Issue by cygri** [apache/jena#1309]
[This line](https://github.com/apache/jena/blob/b74e7fab67f368b6152e033a6a19c47dfcbbdd10/jena-arq/src/main/java/org/apache/jena/sparql/engine/ref/RefEval.java#L80) in `RefEval.evalDS(...)`:
```
List<Binding> list = new ArrayList<>((int)dsg.size()) ;
```
But according to the Javadoc for `DatasetGraph.size()`:
```
/** Get the size (number of named graphs) - may be -1 for unknown */
```
So `-1` should be expected and treated specially to avoid a potential `IllegalArgumentException` for negative initial size.

(We do not use `RefEval` and I have not seen this exception actually occur. I noticed the potential problem when nosing around the source code, looking at callers of `DatasetGraph.size()`.)

**Comment by afs** [comment]
Would you care to submit a PR?
