### ISSUE TITLE
Bulk retrieval and caching with SERVICE clauses

### ISSUE THREAD

**Issue by Aklakan** [apache/jena#1314]
Jena's current approach to fetch bindings for a SERVICE clause is to instantiate the service pattern for each binding.
This issue is about adding support for bulk requests.
Opening this issue to allocate a issue number for my corresponding PR draft.

**Comment by afs** [comment]
Talking of finishing things ... 
... documentation for custom service execution for Wikidata would be good
... the bearer auth should now work for you; it is naturally environment sensitive so the more validation the better

**Comment by Aklakan** [comment]
Updated title because it turned that the bulk retrieval has to be cache-aware if caching is desired. The PR includes a fully streaming caching system that "de-partitions" bulk retrieval responses in order to cache ranges of data on a per-input-binding basis. Conversely, creation of the bulk request considers the ranges of data already present in the cache.

**Comment by Aklakan** [comment]
In the process of implementing this bulk retrieval and caching I have extended the custom service executor system.
I am proposing the following revisions and extensions:

* The original ServiceExectorFactory continues to exist with the same signature but is now called ServiceExecutor. The rationale is that an executor is already a factory for executions.
```java
public interface ServiceExecutor {
   ServiceExecution createExecution(OpService opExecute, OpService original, Binding binding, ExecutionContext execCxt);
}
```

* There is now a new ChainingServiceExectutor which enables implementing chains (much like jetty servlet filters):
```java
public interface ChainingServiceExecutor {
  ServiceExecution createExecution(OpService opExecute, OpService opOriginal, Binding binding, ExecutionContext execCxt, ServiceExecutor chain);
}
```

This allows for passing modified/rewritten ops down the chain - which is not possible with the ServiceExecutor interface.
The `ServiceExecutorRegistry` still exists but now internally holds `ChainingServiceExecutor` instances rather than `ServiceExecutor`.
There is `ServiceExecutorOverRegistry` which abstracts the existing `ServiceExecutorRegistry`.

* The same concept is now repeated for bulk processing:
```java
public interface ServiceExecutorBulk {
  ServiceExecution createExecution(OpService opService, QueryIterator input, ExecutionContext execCxt);
}

public interface ChainingServiceExecutorBulk {
  ServiceExecution createExecution(OpService opService, QueryIterator input, ExecutionContext execCxt, ServiceExecutorBulk chain);
}
```
* There is now a new `ServiceExecutorRegistryBulk` which is essentially the same as `ServiceExecutorRegistry` but with an internal list of `ChainingServiceExecutorBulk` instances.

* By default, `ServiceExecutorRegistryBulk` is initialized with an `ChainingServiceExecutorBulkToSingle` instance which bridges to the non-bulk registry.


This way, caching and bulk retrieval system can be plugged in using
```
ServiceExecutorRegistryBulk.get().chain(new ChainingServiceExecutorBulkSpecial());
```

[ChainingServiceExecutorBulkSpecial](https://github.com/Aklakan/jena/blob/f85548c488c7f7002eb30943cd7469aa84a6c22b/jena-arq/src/main/java/org/apache/jena/sparql/service/impl/ChainingServiceExecutorBulkSpecial.java#L68) addes support for special service iris such as
```
SERVICE <cache:bulk+20:correlate:http://dbpedia.org/sparql> { }
``` 
or equivalently
```
SERVICE <cache:bulk+20:correlate> { SERVICE <http://dbpedia.org/sparql> { } }
```
where:
* bulk+20 requests a bulk size of 20 bindings
* cache enables caching
* correlate performs a naive `Rename.reverseVarRename` such that substitution with the outer variables (regardless of scoping) can be performed. (There is a caveat that this only works reliably if none of the joining variables is projected because otherwise VarFinder will prevent converting OpJoin to OpSequence).

With the revised plugin system it is easy to add/remove this special functionality or add more custom ones.

**Comment by Aklakan** [comment]
A screenshot with cache and correlate in action to give some impression:
![image](https://user-images.githubusercontent.com/839608/171416044-d09bf0dc-0c2f-4fe4-8cd1-8b89e9f754e3.png)

**Comment by afs** [comment]
> This allows for passing modified/rewritten ops down the chain - which is not possible with the ServiceExecutor interface.

Put any state the processing needs as an object in the context carried by the execution context.

This has per execution scope.

**Comment by Aklakan** [comment]
Yes, that's what I am doing already for configuration of bulk sizes or caching as in [ChainingServiceExecutorBulkSpecial.java#L132](https://github.com/Aklakan/jena/blob/322c4d9c9873e867bf9c986951d468edf05b9ee0/jena-arq/src/main/java/org/apache/jena/sparql/service/impl/ChainingServiceExecutorBulkSpecial.java#L132).

What I meant is, that the chaining API allows for passing arguments to whatever service executors remain in the two service executor registries (bulk and non-bulk).

I added a new example to the [CustomServiceExecutor examples](https://github.com/Aklakan/jena/blob/gh-1314/jena-examples/src/main/java/arq/examples/service/CustomServiceExecutor.java#L107) which uses the chaining API - just below the non-chaining version:

In summary:

"Old" approach:
```java
ServiceExecutorFactory relaySef = (opExecute, original, binding, execCxt) -> {
        if (opExecute.getService().equals(WIKIDATA)) {
            opExecute = new OpService(DBPEDIA, opExecute.getSubOp(), opExecute.getSilent());
            // ISSUE: We cannot easily forward the new OpExecute to the remainder of the registered service executors
            // We would have to check at which index 'relaySef' is registered and then manually do the forwarding
            return ServiceExecutorRegistry.httpService.createExecutor(opExecute, original, binding, execCxt);
        }
        return null;
    };
```

Improved API:
```
ChainingServiceExecutor relaySef = (opExecute, original, binding, execCxt, chain) -> {
    if (opExecute.getService().equals(WIKIDATA)) {
        opExecute = new OpService(DBPEDIA, opExecute.getSubOp(), opExecute.getSilent());
    }
    return chain.createExecution(opExecute, original, binding, execCxt);
};
```

**Comment by afs** [comment]
Discussion about improving the SERVICE extension mechanism separately from the extension to do bulk retrieval, caching etc on the PR #1315 .

**Comment by afs** [comment]
Related: correlated subquery / lateral join for subqueries: 
https://www.ontotext.com/blog/graphdb-users-ask-does-graphdb-support-reusing-values-in-sub-selects/

**Comment by Aklakan** [comment]
The reason why at present I like the SERVICE <correlate:> approach is that it gives full control to the user within the SPARQL 1.1 syntax. Caching is most useful with correlated joins so that the result of the right-hand-side is cached for each input binding.

In case you'd prefer an alternative approach please let me know.

**Comment by Aklakan** [comment]
Stardog's approach: https://docs.stardog.com/query-stardog/stored-query-service#correlated-subqueries

**Comment by afs** [comment]
Either. We don't have to stay within strict SPARQL syntax because the meaning of the evaluation is engine specific so custom syntax is not a restriction except on 3rd party UI tools.

(first pass): Stardog looking like "SERVICE" is used only for a stored query but could be extended to "SERVICE { annotate { subquery } }". The meaning variables in "annotate" is quoting.

Ontotext is inline query, possible less clear to the user with the use of VALUES

We can have both! Nice syntax and a forced syntax.

`LOOP (?v1 ?v2) { subquery }` which loops on the LHS.

(there are other kinds of correlated query - EXISTS is a correlated ASK; and like SQL, there could be a filter function "IN { }").

**Comment by Aklakan** [comment]
The advantage of extra LOOP syntax would be that the loop variables can be easily specified.
With the SERVICE approach I was thinking about the rule that any variable *visible* on the lhs and *mentioned* in the rhs would be implicit loop variables.

With regard to caching and bulk retrieval, I think those would remain as options on the SERVICE clause:
The LOOP yields a QueryIterator of input bindings and the service extension would then take care of grouping as many input bindings as it sees fit into batch requests (as it is done right now) - so all options (except for correlate) would still be at the level of the service clause:
```
LOOP (?x) { SERVICE <cache:bulk+20:http://dbpedia.org/sparql> { }
```
(The options may also be represented using your proposed extension syntax extension - something along the lines of `SERVICE <http://dbpedia.org/sparql> ARGS bulk=20 cache`)


Note, that IMHO a clean solution would require making TransformScopeRename aware of correlated joins and scoping of the loop variables. So this feature actually has implications on the core of ARQ. Of course, I'd favor the clean solution :)

**Comment by Aklakan** [comment]
My limited understanding in of the LOOP variables is as follows:
```
?s ?p ?o .
LOOP (?s) {
   ?s ?p ?o # becomes ?s ?/p ?/o
   LOOP (?p) {
     ?s ?p ?o # becomes ?/s ?/p ?//o
   }
   LOOP (?s ?p) {
     ?s ?p ?o # ?s becomes ?s ?/p ?///o
   }
}
```

For my work on the plugin: With the current approach I am just reverting the scope of all variables - it's as if all mentioned variables appeared as loop variables. I'd think for a first version of a service executor plugin marked as experimental its ok to have this behavior documented; the implication is that one might have to be a bit careful of the variable naming in inner queries. This way it's not a blocker for me.

I think I am now working on the last problem for finishing the functionality of the PR: dealing with unknown result set limits in the cache:
A service clause with caching and/or bulk enabled should yield the exact same result as if these modifiers are absent.
This means I need to fiddle in some logic tha considers the 'largest seen result set size on a service so far' and which avoids serving data from cache if it cannot be guaranteed that the invisible result set size limit will be adhered to.

**Comment by afs** [comment]
Ref issue #1387.

**Comment by Aklakan** [comment]
There are now tests that compare the outcomes of queries with different parameters for bulk size and caching enabled/disabled. So far all succeed - whoever reads this and has interest, feel free to come up with more tests.
The jena-serviceenhancer module (under jena-extras) now also has an assembler and a test case to check whether assembly works.
The pom includes an `ext` profile that creates a shaded jar for use with Fuseki.
Launching fuseki with the serviceenhancer jar on the classpath and an appropriate assembler successfully gives access to the enhanced functionality.

Currently the core interfaces of the caching API are in our third party 'aksw-commons' project. I'll try to move this to the module to make it self-contained. The idea would be to have a basic in-memory cache provider part of the module and allow for support for other cache providers (I actually also have a disk based one, but that one could be loaded as a separate plugin via a maven dependency).
The main issue I now have to work on is that the cache API lacks a method to suppress eviction of data ranges that have been scheduled for answering an active query.
Other than that of course cleanup is needed.


One opinion I'm interested in is how the Fuseki integration should work - should it remain an extra module that can be shaded as it is currently done? And if so what would be an appropriate maven profile name?

**Comment by Aklakan** [comment]
![image](https://user-images.githubusercontent.com/839608/176002264-d24e1c17-2930-4c07-b0fa-31ebfb07ab5e.png)

I am quite excited about the progress - finally nice filtering over cached statistics. Once cached, it only took 0.128 seconds to get out the triples per graph over half a billion triples in a TDB2 . The filter statement in the picture runs on the cached result so changing it still makes the query execute instantly. Whether I can finally start with the clean up depends yet on how many more bugs @LorenzBuehmann finds though :)

**Comment by Aklakan** [comment]
The PR is now overall ready for review.

There is a preliminary jena-extras/jena-serviceenhancer/README.md which I will extend in the next days and the javadocs will need another pass too. There are several test cases which may also be a good starting point. Due to vacation progress is a bit slow.

**Comment by afs** [comment]
Document can be after the release though to make impact it is better to have enough for users when you have their attention.

The next Jena release cycle is in the vacation season for many so might be more about preparation/"experimental"/"beta" then do more at the one after that (end October _maybe_).

The choice is yours of how to get the most here.

**Comment by Aklakan** [comment]
@afs Some time ago you mentioned that you unsubscribed from the PR stream so I am just dropping a note here as well that from my side the requested changes were implemented and the PR should be complete for a release of the experimental module.

**Comment by afs** [comment]
I _tried_ to unsubscribe :-) Seems there are numerous ways GH will resubscribe people!

**Comment by afs** [comment]
The associated PR #1315 has been merged.
