### ISSUE TITLE
OpAsQuery incorrect transform of dependent expressions

### ISSUE THREAD

**Issue by Aklakan** [apache/jena#1369]
Something is wrong in OpAsQuery that causes expressions to get lost:
```java
Query before = QueryFactory.create("SELECT ?z { BIND('x' AS ?y) BIND(?y AS ?z) }");
Op op = Algebra.compile(before);
Query after = OpAsQuery.asQuery(op);
System.out.println(after);
```

Expected result:
```sparql
SELECT ?z {
  SELECT  ('x' AS ?y) (?y AS ?z)
  WHERE
    { }
}
```
or equivalently
```sparql
SELECT (?y AS ?z) {
  SELECT  ('x' AS ?y)
  WHERE
    { }
}
```

Actual result:
```sparql
SELECT  (?y AS ?z) // Missing ('x' AS ?y)
WHERE
  {  }
```
It seems its related to projecting only some of the variables and
it may be related to some magic with unit tables - but I'm not sure.

If possible, I'd prefer OpAsQuery to not try to optimize 'unused' binds (isn't that something the optimizer should take care of?).
For example, if the constant `'x'` was replaced with the variable `?x` as in
```java
Query before = QueryFactory.create("SELECT ?z { BIND(?x AS ?y) BIND(?y AS ?z) }");
```
then IMO the expected result should nonetheless be a query that includes all the expressions such as:
```sparql
SELECT ?z {
  SELECT  (?x AS ?y) (?y AS ?z)
  WHERE
  { }
}
```

W.r.t. 'the transformed query must yield same output'-contract an equivalent transformation would actually be
```sparql
SELECT ?z
WHERE
  { }
```
because the other variables are not bound. But then the expressions gets lost which might be undesired.

The reason is, that it may be desired to treat such graph patterns as templates and apply substitutions afterwards - so values would eventually be supplied even if there is a unit table now.

**Comment by afs** [comment]
Simpler: no `?y` reuse for `?z`:

`SELECT ?z { BIND('x' AS ?y) BIND('z' AS ?z) }`

**Comment by afs** [comment]
`OpAsQuery` is not a perfect reversal of the process of compiling the query to algebra. It aims to produce equivalent queries - same output. It has to spot patterns because `SELECT (expr as ?var)` and `SELECT * {   ... BIND (expr as ?var)}` are the same algebra.

When translating algebra to syntax, `OpAsQuery` is spotting this pattern. If you want all the `BIND`, use `SELECT *`.

`SELECT  (?x AS ?y) (?y AS ?z) {}` has two variables, whereas `SELECT ?z {}` has one. It's a different query.

**Comment by Aklakan** [comment]
The problem is that the projection just naively filters the collected assignments without taking dependencies into account:
```
level.opProject.getVars().forEach(v -> {
    if ( assignments.containsKey(v) ) {
        query.addResultVar(v, assignments.get(v)) ;
    } else
        query.getProjectVars().add(v) ;

}) ;
```

**Comment by Aklakan** [comment]
> It aims to produce equivalent queries - same output.

Yes, but in the first example with the constant `'x'` it fails because the output differs.

In the case where there is a variable it would be according to the 'same output' contract - though losing those expressions is not really what I expected.

**Comment by afs** [comment]
> IMO the expected result.

I was speaking about this proposal. It is a different query.

This code has built-up over time with lots of opinion. Outputting a query that is not the input will probably cause users problems, generate a support load and we end up going in circles.

**Comment by Aklakan** [comment]
Oh my, I messed up the expected results because I forgot the projection of ?z - sorry for the confusion.

It needs to be something along the lines of
```
SELECT  (?y AS ?z)
WHERE { SELECT (X AS ?y) WHERE {} } // X either 'x' or ?x
```

**Comment by afs** [comment]
Why not add a detection criterion so that BIND is reversed to a project expression only if the project is safe? This would work down the `(extend)` stack with a "while safe" test. Replace that stream with a for-loop, push back remaining `level.opExtends` into the pattern.

These short examples hide the fact that in real queries, the BIND are at the end of a long pattern. Only BIND at the end are considered. Adding an extra sub-query - even if the same query - is unexpected by users.

**Comment by Aklakan** [comment]
> Why not add a detection criterion so that BIND is reversed to a project expression only if the project is safe?

Yes, that makes sense.

> Adding an extra sub-query - even if the same query - is unexpected by users.

Certainly; I was incorrectly assuming that OpAsQuery due to the 'not perfect reversal' always uses projections but I see it actually does support reversing into BIND. So the detection criterion is what is needed.

**Comment by afs** [comment]
It'll be easiest in the calculation of `level.opExtend` which look like it is `processExtend` (which is used twice).

**Comment by Aklakan** [comment]
I'll look into it

**Comment by afs** [comment]
I'm not working on it.

**Comment by afs** [comment]
Also reported as [JENA-2335](https://issues.apache.org/jira/browse/JENA-2335).

**Comment by jmkeil** [comment]
@Aklakan: Thank you for fixing that.
