### ISSUE TITLE
How to reload data without restart the server? 

### ISSUE THREAD

**Issue by natebowang** [apache/jena#1422]
### Version

4.4.0

### Question

How to reload data without restart the server?

**Comment by afs** [comment]
In a default setup,


Reload - as in replace existing data:

PUT the data, with the Content-Type set, to the dataset URL. Tools such as `curl` can do this.

**Comment by natebowang** [comment]
Thanks for the reply. 

I found the `s-put` in the ./jena-fuseki2/apache-jena-fuseki/bin is pretty handy for this. 
```bash
s-put http://localhost:3030/ds default ./main.ttl
```

The above command will remove the default graph and reload the `main.ttl`. 

Please correct me if it's not true :)
