### ISSUE TITLE
How to presistent TDB2 on AWS? 

### ISSUE THREAD

**Issue by natebowang** [apache/jena#1425]
### Version

4.5.0

### Question

How to presistent TDB2 on AWS?

**Comment by namedgraph** [comment]
You can check this AWS Marketplace product. It persists data on the EC2 instance.

https://aws.amazon.com/marketplace/pp/prodview-vlw4v7stfhqsu

**Comment by afs** [comment]
Apache Jena TDB2 runs with EC2 and EBS or local storage, or in containers. The requirement is a file system.

It is not necessary to run a 3rd party offering.

@namedgraph - the question says "TDB2", not "Fuseki".

**Comment by natebowang** [comment]
Thanks!

**Comment by afs** [comment]
You'll be better off using the project mailing list `users@jena.apache.org` Subscribe by sending email to 

[users-subscribe@jena.apache.org](mailto:users-subscribe@jena.apache.org) then replying to the email it will send you to confirm your request.

Details:
https://jena.apache.org/help_and_support/index.html
