### ISSUE TITLE
Fuseki Query-UI sends request to wrong endpoint

### ISSUE THREAD

**Issue by ramsel1508** [apache/jena#1443]
### Version

4.5.0

### What happened?

# Current behaviour:
Queries in the Fuseki Query-UI are always sent to the query-endpoint. The in put in the input-field "SPARQL Endpoint" seems to be ignored.

![fuseki_query_ui](https://user-images.githubusercontent.com/63793155/179177656-d9ce8e42-4c63-42c2-9fec-f676439717ef.png)

# Desired behaviour:
Input field "SPARQL Edpoint" is considered within sparql query execution

**Comment by kinow** [comment]
Tested using the branch from #1307:

![image](https://user-images.githubusercontent.com/304786/179691802-b70104ee-7232-4a00-9548-78825f4bfddf.png)

It will take a little longer to finish testing that branch, but once that's merged and released, this issue should be fixed :+1: 

-Bruno
