### ISSUE TITLE
NPE: Cannot invoke "String.equals(Object)" because "prefix" is null

### ISSUE THREAD

**Issue by namedgraph** [apache/jena#1450]
### Version

4.5.0

### What happened?

Writing Model as RDF/XML started giving this exception. I cannot pinpoint any changes that could have caused it, the code in this area has been stable for a long time. I can serialize the same model as Turtle (and then re-serialize as RDF/XML using riot CLI) just fine. The data can be provided if it helps.

Some investigation I did:
* `this.getPrefixFor( value )` returns `null`, where value is `http://www.w3.org/2001/XMLSchema#`: https://github.com/apache/jena/blob/main/jena-core/src/main/java/org/apache/jena/rdfxml/xmloutput/impl/BaseXMLWriter.java#L229
* `Relation::backwards` returns `null` because `http://www.w3.org/2001/XMLSchema#` is not in the `cols` map: https://github.com/apache/jena/blob/main/jena-core/src/main/java/org/apache/jena/rdfxml/xmloutput/impl/Relation.java#L204

### Relevant output and stacktrace

```shell
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "prefix" is null
org.apache.jena.rdfxml.xmloutput.impl.BaseXMLWriter.checkLegalPrefix(BaseXMLWriter.java:845)
org.apache.jena.rdfxml.xmloutput.impl.BaseXMLWriter.setNsPrefix(BaseXMLWriter.java:324)
org.apache.jena.rdfxml.xmloutput.impl.BaseXMLWriter.primeNamespace(BaseXMLWriter.java:232)
org.apache.jena.rdfxml.xmloutput.impl.BaseXMLWriter.setupNamespaces(BaseXMLWriter.java:482)
org.apache.jena.rdfxml.xmloutput.impl.BaseXMLWriter.write(BaseXMLWriter.java:466)
org.apache.jena.rdfxml.xmloutput.impl.BaseXMLWriter.write(BaseXMLWriter.java:456)
com.atomgraph.linkeddatahub.server.io.ValidatingModelProvider.write(ValidatingModelProvider.java:129)
```

**Comment by afs** [comment]
> The data can be provided if it helps.

A minimal, reproducible example please.

Minimal code, minimal data. 

Does the example work in previous versions?

**Comment by namedgraph** [comment]
That didn't help... I'll try removing `OntModelReadOnly` usages altogether.

**Comment by namedgraph** [comment]
The NPE went away when I removed my implementation. I'll try to make a standalone example.

**Comment by afs** [comment]
Status? If there isn't anything actionable about Jena, this should be closed.

**Comment by namedgraph** [comment]
Nothing actionable right now because I'm on vacation. Might reopen later when I have time to build a test case.
