### ISSUE TITLE
Cleaning during the UI build process.

### ISSUE THREAD

**Issue by afs** [apache/jena#1488]
The jena-fuseki-ui module does not clean out the cached `node_modules/` and `node/` directories.

Does this matter?

A release build is supposed to work from freshly checked out git.

I found this because the build had the wrong build order:
Was:
```
    <module>jena-fuseki-webapp</module>
    <module>jena-fuseki-ui</module>
```
(fixed now)
so `jena-fuseki-webapp` picked up the previous build output and did not work on a freshly checked out Jena git repo.

Adding to `maven-clean-plugin` is possible but maybe this is too clean because it then requires a node install and a `yarn install` of about 480M.

```
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <configuration>
            <filesets>
              <fileset><directory>node</directory></fileset>
              <fileset><directory>node_modules</directory></fileset>
            </filesets>
          </configuration>
        </plugin>
```

We might be able to make this only happen when profile "-Papache-release" is active. Ideally, it would be done by `release:clean` but I can't see how to add to that operation.

**Comment by kinow** [comment]
>Adding to maven-clean-plugin is possible but maybe this is too clean because it then requires a node install and a yarn install of about 480M.

I think that should be OK? While developing the UI I don't normally call `mvn clean`, only when I switch branches or really want to clean my maven outputs. In which case I think it's far that it cleans the `node_modules` too.

Maybe we can investigate using Yarn PnP (plug-and-play) which removes the need for the `node_modules` directory - <https://yarnpkg.com/features/pnp>

But it would still download Yarn again.

My development workflow is:

1. Check out branch
2. `yarn install`
3. `yarn run serve` or some other Yarn command
4. `git commit ...`

I only use `mvn` when testing the PR, with `mvn -Pdev`, or manually specifying targets.

**Comment by afs** [comment]
OK - let's leave things as they are. It is more like the artifacts in the maven repo. It's not locally built code and it's not small.
