### ISSUE TITLE
HTTP Basic auth Fuseki (shiro.ini) + CORS restriction

### ISSUE THREAD

**Issue by SimonBin** [apache/jena#1516]
### Version

4.7.0-SNAPSHOT

### Question

When securing a data set with authentication, it is in theory possible to query this from **another domain** using XMLHttpRequest

This could be useful to use e.g. the commercial YASGUI with Geo plug-in to visualise data from a log-in protected Fuseki.

To protect our installation, we changed the `shiro.ini` to:
```
# Everything else
/**=authcBasic,user[secretuser]
```

However, it is somewhat more complicated to enable CORS with authentication: [^1]

the OPTIONS "pre-flight" request must be answered without the need to log in. Currently, Fuseki fails at this step

```
curl -vv 'http://localhost:3030/ds/' -X OPTIONS -H 'Access-Control-Request-Headers: authorization' -H 'Origin: http://yasgui.triply.cc'
```

```
< HTTP/1.1 401 Unauthorized
```

it would need to respond with
```
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: http://yasgui.triply.cc
< Access-Control-Allow-Credentials: true
```

has anyone faced this issue before? can it be fixed in Fuseki?

I know it is possible to work around with a reverse proxy that "hacks in" the proper response.... but that is rather cumbersome

[^1]: https://fetch.spec.whatwg.org/#http-responses

**Comment by afs** [comment]
Did you mean https://fetch.spec.whatwg.org/#cors-protocol-and-credentials ?

A common mode of operation, and what Shiro is doing, is to do authentication with servlet filter which is insensitive to the HTTP method. How do other system handle this?

I found
https://stackoverflow.com/questions/60786804/apache-shiro-is-breaking-the-cors-configuration-of-my-spring-boot-restapi
which is about servlet filter order. 

But not all CORS should be before authientication?

**Comment by SimonBin** [comment]
Hi Andy, thanks for the answer. I agree this issue is confusing.

FYI: building fuseki with #1520 does **not** seem to be related to this issue

On the whatwg page, I found this following note:

> **Note**
> For a [CORS-preflight request](https://fetch.spec.whatwg.org/#cors-preflight-request), [request](https://fetch.spec.whatwg.org/#concept-request)’s [credentials mode](https://fetch.spec.whatwg.org/#concept-request-credentials-mode) is always "same-origin", i.e., it **excludes credentials**.

I found this additional resource about OPTIONS: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS

Basically, the web browser will always send an OPTIONS request without any credentials ("CORS-preflight") and the server is supposed to reply with `HTTP/1.1 200 OK` / `Access-Control-Allow-Credentials: true` (no Content is sent)

However, if we add `/**=authcBasic,user[admin]`, then OPTIONS are also password protected and the response is `HTTP/1.1 401 Unauthorized`

Thus, a shiro-protected Fuseki cannot be used with cross-site requests.

You can observe this e.g. in the "Web developer tools > Network" in Firefox.

I also did not have much luck finding any reports about this on the shiro side. I found those 2 unanswered issues/questions from 2014:

- [ ] https://issues.apache.org/jira/browse/SHIRO-508
- [ ] https://lists.apache.org/thread/5s1j5l49bl282cd0xodyw5l1vzkrcqjh

**Comment by afs** [comment]
> FYI: building fuseki with https://github.com/apache/jena/pull/1520 does not seem to be related to this issue

There was a discussion on Jetty lists about CORS+auth but I couldn't find a raised issue.
https://www.eclipse.org/lists/jetty-users/msg08899.html

It was good to do it anyway. It's unfortunate Fuseki needs its own copy at the moment.

My long term plan is to consolidate on Fuseki Main and not have a webapp except keeping the WAR file around. i.e. change the standalone JAR. Fuseki modules will add the admin and UI functionality - this has been prototyped but still some way from being ready.

We don't get any benefit from being a webapp - the war file has always seemed to be little used compared to the standalone jar. 

What with containers and cloud, FusekiMain, with configurable modules makes more sense.

**Comment by SimonBin** [comment]
Hi Andy, good news. Your PR made me revisit the CORS source code and there is a -- let's say "workaround" -- in the CORS code that can make it completely stop the filter + servlet chain and create a fake preflight OPTIONS response.

**Comment by afs** [comment]
Hi @SimonBin,

That'll do - if I understand CORS and the code (big _if_), the filter only shortcuts preflight OPTIONS, not all OPTIONS. That's good.

Fuseki/Main will need a similar change and also reverse the auth and CORS filters which I'll do.
