### ISSUE TITLE
JenaSystem.init NPE when run jar built from kotlin-gradle project

### ISSUE THREAD

**Issue by sszuev** [apache/jena#1556]
### Version

4.6.1

### What happened?

```
java 11.0.15 2022-04-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.15+8-LTS-149, mixed mode)
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.15 (Oracle Corporation 11.0.15+8-LTS-149)
OS:           Linux 5.10.16.3-microsoft-standard-WSL2 amd64
```
Commands to build & run:
```bash
$ gradle clean build
$ java -jar build/libs/test-jena-init-1.0-SNAPSHOT.jar
```
Test app:
```kotlin
package com.gitlab.sszuev.investigation

import org.apache.jena.query.QueryExecution

object JenaInitInvestigation {
    init {
        org.apache.jena.sys.JenaSystem.init()
        //org.apache.jena.riot.RIOT.init()
        //org.apache.jena.query.ARQ.init()
    }

    @JvmStatic
    fun main(args: Array<String>) {
        println("Go")
        val endpoint = "http://xxx.example.com/sparql"
        val queryString = "CONSTRUCT { ?s ?p ?o } WHERE { ?s ?p ?o }"
        val m = QueryExecution.service(endpoint).query(queryString).build().execConstruct()
        println(m.size())
    }
}
```
build.gradle
```gradle
plugins {
    id "org.jetbrains.kotlin.jvm" version "1.7.10"
}

group 'com.gitlab.sszuev'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib', version: '1.7.10'
    implementation 'org.apache.jena:jena-arq:4.6.1'
}

jar {
    zip64 true
    manifest {
        attributes(
                'Main-Class': 'com.gitlab.sszuev.investigation.JenaInitInvestigation',
                'Implementation-Title': 'JenaInitTesting',
                'Implementation-Version': archiveVersion,
                "Multi-Release": true,
                "Manifest-Version": "1.0",
        )
    }
    duplicatesStrategy = 'include'
    from {
        configurations.runtimeClasspath.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}
```

workaround - uncomment `org.apache.jena.query.ARQ.init()`

project: 
[test-jena-init.tar.gz](https://github.com/apache/jena/files/9656288/test-jena-init.tar.gz)

### Relevant output and stacktrace

```shell
Exception in thread "main" java.lang.NullPointerException
        at org.apache.jena.query.ARQ.isTrue(ARQ.java:680)
        at org.apache.jena.sparql.lang.QueryParserBase.<init>(QueryParserBase.java:322)
        at org.apache.jena.sparql.lang.SPARQLParserBase.<init>(SPARQLParserBase.java:40)
        at org.apache.jena.sparql.lang.arq.ARQParserBase.<init>(ARQParserBase.java:35)
        at org.apache.jena.sparql.lang.arq.ARQParser.<init>(ARQParser.java:8071)
        at org.apache.jena.sparql.lang.ParserARQ.perform(ParserARQ.java:90)
        at org.apache.jena.sparql.lang.ParserARQ.parse$(ParserARQ.java:52)
        at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:33)
        at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:144)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:83)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:56)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:44)
        at org.apache.jena.http.sys.ExecHTTPBuilder.query(ExecHTTPBuilder.java:89)
        at com.gitlab.sszuev.investigation.JenaInitInvestigation.main(JenaInitInvestigation.kt:17)
```

**Comment by rvesse** [comment]
I'm not familiar with Gradle but it looks like you are maybe building a fat JAR with all your dependencies in it?

If this is the case then you are likely running into an issue that Jena initialisation is driven by `ServiceLoader` where each separate Jena library has a file in `META-INF/services` defining the system initialisers it uses.  Your repackaging is likely picking only one of files (because the `ServiceLoader` mechanism requires they have the same name in every library JAR file) thus resulting in partial initialisation.

See https://jena.apache.org/documentation/notes/jena-repack.html for notes on how to successfully repack Jena into a fat JAR

**Comment by afs** [comment]
StackOverflow suggests some file manipulations to do this but now there seems to be gradle plugin to do this (haven't tried it):

https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow/7.0.0

https://imperceptiblethoughts.com/shadow/configuration/merging/#merging-service-descriptor-files

@sszuev If it works could you send a PR to update the documentation? Thanks.

**Comment by sszuev** [comment]
> I'm not familiar with Gradle but it looks like you are maybe building a fat JAR with all your dependencies in it?
> 
> If this is the case then you are likely running into an issue that Jena initialisation is driven by `ServiceLoader` where each separate Jena library has a file in `META-INF/services` defining the system initialisers it uses. Your repackaging is likely picking only one of files (because the `ServiceLoader` mechanism requires they have the same name in every library JAR file) thus resulting in partial initialisation.
> 
> See https://jena.apache.org/documentation/notes/jena-repack.html for notes on how to successfully repack Jena into a fat JAR

Indeed,
with the described configuration I have following zip-entries in my jar:
```
==========================================
META-INF/services/org.apache.jena.sys.JenaSubsystemLifecycle
org.apache.jena.riot.system.InitRIOT
org.apache.jena.sparql.system.InitARQ
org.apache.jena.rdfs.sys.InitRDFS

==========================================
META-INF/services/org.apache.jena.sys.JenaSubsystemLifecycle
org.apache.jena.sys.InitJenaCore
```

the `com.github.johnrengelman.shadow` plugin works fine, I have now single zip-entry with all 4 records inside.

the official doc (https://jena.apache.org/documentation/notes/jena-repack.html) seems to be good enough,
but probably a few more words can be added.

**Comment by sszuev** [comment]
> StackOverflow suggests some file manipulations to do this but now there seems to be gradle plugin to do this (haven't tried it):
> 
> https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow/7.0.0
> 
> https://imperceptiblethoughts.com/shadow/configuration/merging/#merging-service-descriptor-files
> 
> @sszuev If it works could you send a PR to update the documentation? Thanks.

minor changes in docs: 
https://github.com/apache/jena-site/pull/123
