### ISSUE TITLE
Incorrect Dataset supportsTransactions()

### ISSUE THREAD

**Issue by ebremer** [apache/jena#1559]
### Version

4.6.1

### What happened?

These all report true
```
System.out.println(DatasetFactory.create().supportsTransactions());
System.out.println(DatasetFactory.createTxnMem().supportsTransactions());
System.out.println(DatasetFactory.createGeneral().supportsTransactions());
```
I thought only DatasetFactory.createTxnMem().supportsTransactions() would be true.......

**Comment by afs** [comment]
The other two provide begin-commit/abort. They give isolation through an MRSW lock - multiple-reader OR one writer semantics.

Any writer locks out readers but the isolation contact of begin-commit/abort is provided. That worse that TIM (Transaction In Memory/TxnMem).

But any code using transactions should be able to use the general daatsets for execution time transaction isolation.

**Comment by ebremer** [comment]
Understood.  Thank you.
