### ISSUE TITLE
java: package org.apache.jena.ext.com.google.common.cache does not exist

### ISSUE THREAD

**Issue by tangg555** [apache/jena#1608]
### Version

Apache Jena Fuseki 4.6.1

### Question

It is exactly the same problem to this link [https://stackoverflow.com/questions/39923563/package-org-apache-jena-ext-com-google-common-cache-does-not-exist-in-intellij](https://stackoverflow.com/questions/39923563/package-org-apache-jena-ext-com-google-common-cache-does-not-exist-in-intellij). However, there is no any solution to address this error.

I use the latest version of IntelliJ, and my jave version is 1.17. If I can address this issue if I change to Ellipse or use Jave 1.11 as the homepage required?

**Comment by kinow** [comment]
I think this should be a discussion, not an issue?

**Comment by afs** [comment]
@tangg555 -- presumable like the SO link, you downloaded the source.

IntelliJ does not seem to understand the shaded jar module.

Run `mvn clean install -Pdev` which will create the jar necessary (and the rest of the main Jena modules but that is a sideeffect).

Please let us know if that works.

Java version does not matter. Any java > 11 should work.

**Comment by afs** [comment]
@tangg555 - did you get things working?

**Comment by afs** [comment]
Presumed answered.
