### ISSUE TITLE
Service Enhancer Order By and Union Default Graph Issue

### ISSUE THREAD

**Issue by Aklakan** [apache/jena#1656]
### Version

4.7.0-SNAPSHOT

### What happened?

This is the bug report for the upcoming PR that solves the following 2 issues with the service enhancer plugin:

* A bug in the bulk-query rewriter of the service enhancer omits the ORDER BY on the final query when both LIMIT and ORDER BY are present on the sub-query being looped over:
```sparql
SELECT * {
  VALUES ?s { <foo> <bar> }
  SERVICE <loop:> {
    SELECT * { ?s rdfs:label ?l } ORDER BY ?l LIMIT 1
  }
}
```
The members of the generated UNION query incorrectly lack the ORDER BY clause.

* We noticed and fixed an issues with the service enhancer on a TDB with default union graph enabled where unexpectedly  triple patterns would not matched against the default graph anymore: 
```
?s ?p ?o # This pattern matches correctly against the union default graph
SERVICE <{loop|cache|bulk}:> { ?o ?x ?y } # Used to not match against the default graph anymore.
``` 

In essence the solution is to use QueryEngineRegistry (which gives all registered plugins a chance to do their processing) rather than QC.execute.

### Are you interested in making a pull request?

Yes

**Comment by afs** [comment]
@Aklakan - GH [automatically closes issues](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) if the description has:

"resolved #1656" 
"fixes #1656" 
...

but not 

> Fixed issues mentioned in ...
