### ISSUE TITLE
Add support for using-graph-uri/using-named-graph-uri parameter in Fuseki SPARQL Update

### ISSUE THREAD

**Issue by user-cjw** [apache/jena#1665]
### Version

4.6.1

### Feature

As recommended in W3C standard [SPARQL1.1-Protocol](https://www.w3.org/TR/sparql11-protocol/#update-operation), since Fuseki already supports _default-graph-uri_ parameter in query operation, it will be better to support _using-graph-uri_ parameter in update operation as well

> 06:26:35 WARN  Fuseki          :: SPARQL Update: Unrecognized request parameter (ignored): using-graph-uri
06:26:35 INFO  Fuseki          :: [91] Update
06:26:36 INFO  Fuseki          :: [91] 204 No Content (450 ms)

### Are you interested in contributing a solution yourself?

None

**Comment by rvesse** [comment]
Please could you provide a complete example of how you reproduced this issue?

Looking at the code Fuseki does support these parameters, **BUT** per the specification you linked where these parameters are permitted, i.e. whether you can use them in the query string, depends on the `Content-Type` you are `POST`ing to the server.

So this may be a case of user/application error.  But it's also possible that the request validation logic is wrong in some way.   However, without a complete test case to reproduce the issue I can't say either way

**Comment by user-cjw** [comment]
Ok... After rereading the server logs, the problem is caused by unexpected space after the parameter name. sorry for that.
