### ISSUE TITLE
Support for 'q' flag in regex

### ISSUE THREAD

**Issue by namedgraph** [apache/jena#1667]
### Version

4.5.0

### Feature

This is a useful flag for passing a string as-is:
> if present, all characters in the regular expression are treated as representing themselves, not as metacharacters. In effect, every character that would normally have a special meaning in a regular expression is implicitly escaped by preceding it with a backslash.
> Furthermore, when this flag is present, the characters $ and \ have no special significance when used in the replacement string supplied to the [fn:replace](https://www.w3.org/TR/xpath-functions-31/#func-replace) function.

https://www.w3.org/TR/xpath-functions-31/#flags

### Are you interested in contributing a solution yourself?

Perhaps?

**Comment by afs** [comment]
It's already supported.

```
ASK { FILTER REGEX("str*str", "*", "q")}
```

**Comment by namedgraph** [comment]
Okay... I misunderstood "there's only one flag" in #1666 being about `regex`. Sorry bout that.
