### ISSUE TITLE
Add "--noBase" to riot.

### ISSUE THREAD

**Issue by afs** [apache/jena#1672]
### Version

4.6.1

### Feature

Add a parsing mode where no base is passed to the reader and relative URIs are passed through.

This is a "best effort" feature with no guarantee that every parser will support unresolved relative URIs and that the parsed results are useful.

For example, N-Triples requires resolved URIs and any generated N-Triples will not comply with the N-Triples specification.

Writing RDF/XML requires resolved URIs.

Parser warnings may still be generated.

### Are you interested in contributing a solution yourself?

Yes

**Comment by kinow** [comment]
Just had a quick look at the ARQ docs online. Would it be the first camelcased arg? If yes, maybe we could use `--nobase`, I think we already have `--namedgraph` in some sub/command? Thanks!

**Comment by afs** [comment]
Both are supported :-) 

It's not case insensitive, that would mess with the natural single latter argument styles, it's because arguments can have multiple names. 

nobase, noBase
namedGraph, namedgraph

**Comment by kinow** [comment]
That's clever! #TodayILearned! :rofl: 

Thanks Andy
