### ISSUE TITLE
Add SPARQL function ADJUST which adjusts the timezone of time and date related datatypes.

### ISSUE THREAD

**Issue by afs** [apache/jena#1706]
### Version

4.7.0

### Feature

This is taken from https://github.com/w3c/sparql-12/blob/main/SEP/SEP-0002/sep-0002.md. It is the generalization of F&O functions on special datatypes.

`xsd:dateTime ADJUST(xsd:dateTime arg, xsd:dayTimeDuration timezone)` ([fn:adjust-dateTime-to-timezone](https://www.w3.org/TR/xpath-functions/#func-adjust-dateTime-to-timezone))

`xsd:date ADJUST(xsd:date arg, xsd:dayTimeDuration timezone)` ([fn:adjust-date-to-timezone](https://www.w3.org/TR/xpath-functions/#func-adjust-date-to-timezone))

`xsd:time ADJUST(xsd:time arg, xsd:dayTimeDuration timezone)` ([fn:adjust-time-to-timezone](https://www.w3.org/TR/xpath-functions/#func-adjust-time-to-timezone))

### Are you interested in contributing a solution yourself?

Yes

**Comment by kinow** [comment]
Today-I-Learned. Had no idea you could do that in SPARQL. If I had to do that, I'd probably do that outside of SPARQL. Thanks!
