### ISSUE TITLE
Broken link on Jena RDFS Inferencing documentation page

### ISSUE THREAD

**Issue by CaptSolo** [apache/jena#1736]
### Version

4.7.0

### What happened?

The [Data with RDFS Inferencing](https://jena.apache.org/documentation/rdfs/) page has a broken link with text `Jena RDFS Reasoner support` pointing to `https://jena.apache.org/inference/`.

Perhaps it should point to `https://jena.apache.org/documentation/inference/#rdfs` instead.

### Are you interested in making a pull request?

None

**Comment by kinow** [comment]
>Perhaps it should point to https://jena.apache.org/documentation/inference/#rdfs instead.

+1 @CaptSolo would you like to send a pull request to https://github.com/apache/jena-site? https://github.com/apache/jena-site/blob/main/source/documentation/rdfs/__index.md

Cheers

**Comment by CaptSolo** [comment]
> +1 @CaptSolo would you like to send a pull request to https://github.com/apache/jena-site? https://github.com/apache/jena-site/blob/main/source/documentation/rdfs/__index.md

Thanks. 

Done: https://github.com/apache/jena-site/pull/143
