### ISSUE TITLE
Return unexpected results when query numbers

### ISSUE THREAD

**Issue by Cynthia-77** [apache/jena#1750]
### Version

3.3.0

### What happened?

Write the following RDF data into Jena:

```turtle
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
<http://John> <http://have> 10 .
<http://Peter> <http://have> "10"^^xsd:double .
```

Then execute the following query:

```
SELECT *
WHERE { ?s ?p 10. }
```

The query result is:

| ?s                  | ?p                  |
| ------------------- | ------------------- |
| ```<http://John>``` | ```<http://have>``` |

```"10"^^xsd:double``` has the value 10 as well. Why can't I obtain it through the query?

The expected query result is:

| ?s                   | ?p                  |
| -------------------- | ------------------- |
| ```<http://John>```  | ```<http://have>``` |
| ```<http://Peter>``` | ```<http://have>``` |

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
In `{ ?s ?p 10. }`, 10 (the dot is the triple pattern separator) is shorthand for `"10"^"xsd:integer`.

This is RDF term equality - same datype.

To get value-equity, use a FILTER
`{ ?s ?p ?x . FILTER(?x = 10) }`

----
> 3.3.0

The current Jena version is 4.7.0.

3.3.0 was released in 2017.

**Comment by afs** [comment]
https://stackoverflow.com/questions/75399559/marklogic-seems-not-to-follow-the-rdf-specification
