### ISSUE TITLE
using-graph-uri parameter not working as expected

### ISSUE THREAD

**Issue by user-cjw** [apache/jena#1758]
### Version

4.6.1

### What happened?

According to specification [SPARQL 1.1 Protocol](https://www.w3.org/TR/sparql11-protocol/), we should be able to select default working graph using _using-graph-uri_ parameter for insert/delete operations with POST update interface. For example, with following query
```
POST /test/?using-graph-uri=http%3A%2F%2Fexample.org%2F HTTP/1.1
Host: <fuseki server>
Content-Type: application/sparql-update
Content-Length: 92

PREFIX ex: <http://example.org/>
INSERT {?ent a ex:Object}
WHERE {BIND(ex:Entity AS ?ent)}
```
The tripple should be inserted into graph _<http://example.org/>_ , but actually it will be inserted into **default graph** instead, no matter if I use insert or insert data. 
Only when I explicitly specify the graph name in SPARQL, it will insert the tripple into the graph correctly:
```
POST /test/ HTTP/1.1
Host: <fuseki server>
Content-Type: application/sparql-update
Content-Length: 120

PREFIX ex: <http://example.org/>
WITH <http://example.org/>
INSERT {?ent a ex:Object}
WHERE {BIND(ex:Entity AS ?ent)}
```
After more tests, I find that the parameter itself is recognized, but not function correctly afterwards. I mean with following example:
```
POST /test/?using-graph-uri=http%3A%2F%2Fexample.org%2F HTTP/1.1
Host: <fuseki server>
Content-Type: application/sparql-update
Content-Length: 120

PREFIX ex: <http://example.org/>
WITH <http://example.org/>
INSERT {?ent a ex:Object}
WHERE {BIND(ex:Entity AS ?ent)}
```
Fuseki does complain the conflict between _WITH_ keyword and _using-graph-uri_ parameter
```
ActionErrorException with cause
org.apache.jena.fuseki.servlets.ActionErrorException: SPARQL Update: Protocol using-graph-uri or using-named-graph-uri present where update request has USING, USING NAMED or WITH
```

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
The update has a `WITH`. It can't be mixed with using-graph-uri.

WITH and USING/using-graph-uri are both affecting the choices of graphs so they interact.

The spec of protocol says it's an error (not a Jena design decision)

SPARQL Update: Protocol using-graph-uri or using-named-graph-uri present where update request has USING, USING NAMED or WITH

https://www.w3.org/TR/sparql11-protocol/#update-dataset

**Comment by user-cjw** [comment]
Thank you for the explanation of the USING keyword
