### ISSUE TITLE
Jena Fuseki sometimes cuts off miliseconds of an xsd:dateTime timestamp

### ISSUE THREAD

**Issue by GreenfishK** [apache/jena#1810]
### Version

4.3.2

### What happened?

Consider following insert statements of two triples. 
```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT DATA
{ 
  	<http://example.com/s1> <http://example.com/p1> "2021-06-02T12:00:00.000+02:00"^^xsd:dateTime . 
	<http://example.com/s1> <http://example.com/p1> "9999-12-31T00:00:00.000+02:00"^^xsd:dateTime .
}
```
Upon execution Jena cuts of the miliseconds of the first triple but doesn't do that for the second triple. Here are the raw results:

```
{ "head": {
    "vars": [ "s" , "p" , "o" ]
  } ,
  "results": {
    "bindings": [
      { 
        "s": { "type": "uri" , "value": "http://example.com/s1" } ,
        "p": { "type": "uri" , "value": "http://example.com/p1" } ,
        "o": { "type": "literal" , "datatype": "http://www.w3.org/2001/XMLSchema#dateTime" , "value": "9999-12-31T00:00:00.000+02:00" }
      } ,
      { 
        "s": { "type": "uri" , "value": "http://example.com/s1" } ,
        "p": { "type": "uri" , "value": "http://example.com/p1" } ,
        "o": { "type": "literal" , "datatype": "http://www.w3.org/2001/XMLSchema#dateTime" , "value": "2021-06-02T12:00:00+02:00" }
      }
    ]
  }
}
```

Why is that? 

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
Presumably you are using the TDB1 or TDB2 as the database.

In TDB2 some nodes are stored by value. (TDB1 has a slightly smaller set) Various forms of numbers (integers, decimals, floats, doubles) as well as xsd:dateTimes.

For all these, the value is stored only if it is inside the coding range. Very large integers are not encoded.

For dateTime the years must be within 0-7999 to be value-encoded.

If value encoded, the lexical form is not preserved; a canonical form is returned. For xsd;dateTime, if the fractional seconds are zero, they are not added to the lexical form.

`"2021-06-02T12:00:00.000+02:00"^^xsd:dateTime` gets encoded as a value, and with/without zero fractional seconds is not retained.

`"9999-12-31T00:00:00.000+02:00"^^xsd:dateTime` is outside the range so the original lexical form is stored.

**Comment by GreenfishK** [comment]
I see, thank you!
