### ISSUE TITLE
Unclosed InputStream

### ISSUE THREAD

**Issue by irvingans** [apache/jena#1840]
### Version

3.16.0

### What happened?

I recently came across a bug in the source code where an InputStream is not closed properly. This could potentially lead to memory leaks and other issues.

The code in question can be found in
https://github.com/apache/jena/blob/main/jena-tdb1/src/main/java/org/apache/jena/tdb/setup/StoreParamsCodec.java. 

Specifically, the InputStream
![image](https://user-images.githubusercontent.com/70804456/230864775-0ecb037c-c6cd-4359-aa57-0b299ae4fbc7.png)

is not being closed after use.

I would like to report this issue and request that it be addressed in a future release. Closing the InputStream after use will prevent potential memory leaks and ensure proper resource management.
![3](https://user-images.githubusercontent.com/70804456/230865502-5192f4e7-afcc-45bc-b429-5b2be9baae04.PNG)

### Are you interested in making a pull request?

Yes

**Comment by kinow** [comment]
From what I remember, there are input streams that are intentionally left open, and the caller is responsible for closing them.

That code is normally for internal use. Were you using it for processijg data with Jena?

(In Apache Commons components we also have methods where streams are left open for the same reason - so it is not so uncommon.... we just document and ignore linter issues).

Cheers

Bruno

**Comment by afs** [comment]
Please do send in a PR.

There are two StoreParamsCodec classes. The TDB1 and TDB2 codebases are separate.

**Comment by irvingans** [comment]
Hi @kinow Bruno,
![image](https://user-images.githubusercontent.com/70804456/231987183-bbe87e92-4952-43af-9053-10e453252550.png)
Based on you last reply, are you saying if I do data processing with Jena, I should add some stream-closing mechanism myself in my code. If so, how should I do that?

**Comment by afs** [comment]
If the app passed a stream in, then the app should close it. If a stream is returned from a call, the app takes responsibility to close it.  But the common case is the app passes in a filename, eg to be parsed, then Jena closes the stream.
