### ISSUE TITLE
gpg: key 04C95136D236A58F: new key but contains no user ID - skipped

### ISSUE THREAD

**Issue by mathjeff** [apache/jena#1850]
### Version

4.7.0

### What happened?

I'm attempting to establish trust for Jena (in our Gradle build)

When I check the signature of  jena-arg-4.7.0.pom.asc it tells me it was signed with RSA key D99038A1731B8B31B71549EF04C95136D236A58F :

```
 gpg --decrypt jena-arq-4.7.0.pom.asc
gpg: assuming signed data in 'jena-arq-4.7.0.pom'
gpg: Signature made Tue 27 Dec 2022 10:27:46 AM EST
gpg:                using RSA key D99038A1731B8B31B71549EF04C95136D236A58F
gpg: Can't check signature: No public key
```

Then when I ask `gpg` to import this key:

```
gpg --recv-keys D99038A1731B8B31B71549EF04C95136D236A58F
gpg: key 04C95136D236A58F: new key but contains no user ID - skipped
gpg: Total number processed: 1
gpg:           w/o user IDs: 1
```

it tells me that it is skipping importing the key because it contains no user ID

Is it possible to make it easier to automatically import the key for this artifact?

Thanks

### Are you interested in making a pull request?

None

**Comment by kinow** [comment]
Hi @mathjeff ,

Did you import the key from the file linked in “PGP KEYS” at https://jena.apache.org/download/index.cgi? I did that, then went to <https://central.sonatype.com/?smo=true> and searched for `org.apache.jena`, searched for jena-arq and downloaded ` jena-arg-4.7.0.pom.asc` from <https://repo1.maven.org/maven2/org/apache/jena/jena-arq/4.7.0/>.

```bash
kinow@ranma:~/Downloads$ gpg --recv-keys D99038A1731B8B31B71549EF04C95136D236A58F
gpg: key 04C95136D236A58F: "Andy Seaborne (Code signing key) <andy@apache.org>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

>Is it possible to make it easier to automatically import the key for this artifact?

I believe we are following the requirements set by the ASF to publish the artefacts. Not sure if the keys could/have to be uploaded to public keyservers too, to make it easier for users to query it. But for now you should be able to have the user ID after importing the `KEYS` file.

**Comment by afs** [comment]
It's in the MIT keyserver.

**Comment by mathjeff** [comment]
Thanks

Interestingly enough, I didn’t manage to get a successful import from what I think is the MIT keyserver:

```
gpg --keyserver pgp.mit.edu --recv-keys D99038A1731B8B31B71549EF04C95136D236A58F                                                       
gpg: keyserver receive failed: No data
```

But after some looking around I think I got a successful key import from [keyserver.ubuntu.com](http://keyserver.ubuntu.com/)

```
gpg --keyserver keyserver.ubuntu.com --recv-keys D99038A1731B8B31B71549EF04C95136D236A58F
gpg: /usr/local/google/home/jeffrygaston/.gnupg/trustdb.gpg: trustdb created
gpg: key 04C95136D236A58F: public key "Andy Seaborne (Code signing key) <andy@apache.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
If that seems reasonable I think this can be closed

Thanks
