### ISSUE TITLE
Remove thread for GeosparqlServer

### ISSUE THREAD

**Issue by afs** [apache/jena#1854]
The GeoSPARQL server (`org.apache.jena.fuseki.geosparql.GeosparqlServer`) holds a reference to the Fuseki server.

The `GeosparqlServer` object is itself a thread and `run()` is a call to `fuseki.start` ... which itself is starting Jetty and the HTTP threads.

The GeoSPARQL server then uses a shutdown hook to stop.

This is unnecessary. The GeoSPARQL server can invoke `fuseki.start` and `fuseki.stop` from the calling thread.

The extra layer of threads and the async shutdown hook cause the tests to be unstable on GH actions (long thread pauses are not uncommon).

**Comment by kinow** [comment]
So that's what was causing the tests to fail and the need for sleep? Nice catch!!!
