### ISSUE TITLE
`BlockUTF8.fromCharsBuffer` contains effectively unreachable code

### ISSUE THREAD

**Issue by Marcono1234** [apache/jena#1863]
### Version

ba2cdb6211f60d7725d779a8556266a8c0b2d0c5

### What happened?

The following lines are effectively unreachable:
https://github.com/apache/jena/blob/ba2cdb6211f60d7725d779a8556266a8c0b2d0c5/jena-base/src/main/java/org/apache/jena/atlas/io/BlockUTF8.java#L199-L216

The reason for this is that `ch` is a `char`, so its value can never be greater than `0xFFFF`.

### Are you interested in making a pull request?

No

**Comment by afs** [comment]
Hi @Marcono1234 - thank you for pointing that out.

The code records what would happen for general UTF-8 encoding, if Java did have full Unicode characters beyond the basic plane and if Unicode goes beyond it's current limit of  0x10FFFF (21 bits). The additional code is harmless and "for reference".

I've added an explanatory comment (on my "small items `misc` branch) to explain the situation.
