### ISSUE TITLE
Replacement for `RecursiveElementVisitor`

### ISSUE THREAD

**Issue by lolgab** [apache/jena#1887]
### Version

4.8.0

### Question

I saw that `RecursiveElementVisitor` was removed in https://github.com/apache/jena/pull/1631
I wanted to ask you what should I use as a replacement.
I wanted to update https://github.com/TopQuadrant/shacl to the latest version of Jena and it [was using it](https://github.com/TopQuadrant/shacl/blob/d7212a53277b081271ebd1a6583c4b2f4edc64e5/src/main/java/org/topbraid/shacl/validation/sparql/SPARQLSyntaxChecker.java#L64).

**Comment by afs** [comment]
`RecursiveElementVisitor` is a do-nothing class that wasn't being used in Jena. The contract wasn't getting maintained. 

Ideally, use a regular `ElementVisitor`. The SHACL code is all "startElement" calls so it look like `ElementVisitor.visit` will work.

Otherwise, take a copy of the code.
