### ISSUE TITLE
Fuseki UI: broken pages

### ISSUE THREAD

**Issue by flange-ipb** [apache/jena#1896]
### Version

4.8.0

### What happened?

Hello,

several pages in Fuseki's UI seem to be broken due to missing files in the published artifacts (_jena-fuseki-ui-4.8.0.jar_, _apache-jena-fuseki-4.8.0.tar.gz_ and _apache-jena-fuseki-4.8.0.zip_).

Broken pages:
- _add data_ to a dataset (requests _static/js/datasetUpload.bebfde8d.js_)
- _edit_ dataset (requests _static/css/datasetEdit.b82e2c17.css_)
- show _tasks_ (requests _static/js/tasks.74e4db94.js_)
- _help_ (requests _static/js/documentation.56eee83a.js_)

The requested files do not exist, maybe their routes changed?

### Are you interested in making a pull request?

No

**Comment by flange-ipb** [comment]
I'm sorry, false alarm! This is a caching problem of my browser, because I worked with 4.7.0's UI before. :unamused:

**Comment by kinow** [comment]
> I'm sorry, false alarm! This is a caching problem of my browser, because I worked with 4.7.0's UI before. unamused

Whew. Thanks for updating the issue @flange-ipb !
