### ISSUE TITLE
Reconfiguration failed when running Apache Jena Binary Distribution

### ISSUE THREAD

**Issue by larisa1995** [apache/jena#1911]
### Version

apache-jena-4.8.0.zip

### What happened?

When running Apache Jena Binary Distribution I get a reconfiguration error. Jena seems to work fine, meaning I get the expected result when running SPARQL queries. Still, I would be grateful if you could tell me how to fix an error.

PS C:\jena> sparql.bat --version
ERROR StatusLogger Reconfiguration failed: No configuration found for '2a139a55' at 'null' in 'null'
Jena:       VERSION: 4.8.0
Jena:       BUILD_DATE: 2023-04-20T08:38:51Z

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
Hi @larisa1995 

Yes, the Jena command will continue and work. The error is about setting up logging.

Where is sparql.bat installed in the filing system?
Are you setting any of the environment variables JENA_HOME, JENAROOT or LOGGING?
Did you previously use a version of Jena where this message did not appear?

**Comment by afs** [comment]
(I'm not a MS Windows user, so I'm hoping someone who does use that OS can help.)

Minor : Ref [2] is out of date - use `JENA_HOME` is preferred.

Not setting `LOGGING` is normal.

Would you be able to change the bat file and printout the value of `%LOGGING%` just before the `java` line at the end?

**Comment by larisa1995** [comment]
Dear @afs 

Please see the changed sparql.bat code and the command line output below. I hope this fits your request.

`@echo off
@rem Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

if "%JENAROOT%" == "" goto :rootNotSet
set JENA_HOME=%JENAROOT%
:rootNotSet

if NOT "%JENA_HOME%" == "" goto :okHome
echo JENA_HOME not set
exit /B

:okHome
set JENA_CP=%JENA_HOME%\lib\*;
set LOGGING=file:%JENA_HOME%/log4j2.properties

echo %LOGGING%

@rem JVM_ARGS comes from the environment.
java %JVM_ARGS% -Dlog4j.configurationFile="%LOGGING%" -cp "%JENA_CP%" arq.sparql %*
exit /B`

C:\apache-jena-4.8.0>sparql.bat --version
file:C:\apache-jena-4.8.0/log4j2.properties
ERROR StatusLogger Reconfiguration failed: No configuration found for '5b37e0d2' at 'null' in 'null'
Jena:       VERSION: 4.8.0
Jena:       BUILD_DATE: 2023-04-20T08:38:51Z

**Comment by rvesse** [comment]
Looks like an erroneous forward slash instead of a backslash in the definition of the bay script where `LOGGING` is defined

Could you try changing that to use a backwards slash instead and see if that resolves the problem?

**Comment by afs** [comment]
What might be confusing log4j is the `file:` part in conjunction with the `C:` and `\`. 
The documentation for log4j2 says that `log4j.configurationFile` takes either a URL, or a file name. `file:C:\` is a mixture.

In which case removing the `file:` may help:

`set LOGGING=file:%JENA_HOME%/log4j2.properties`
to 
`set LOGGING=%JENA_HOME%\log4j2.properties`

or set JENA_HOME to /apache-jena-4.8.0 (no drive letter, assuming everything is on C:)

**Comment by larisa1995** [comment]
Dear @rvesse 

Please see below the changed bat (forward slash changed to backward one) file, the output and a screenshot of directory to answer your third question.

---------------------------------------------------------

@echo off
@rem Licensed under the terms of http://www.apache.org/licenses/LICENSE-2.0

if "%JENAROOT%" == "" goto :rootNotSet
set JENA_HOME=%JENAROOT%
:rootNotSet

if NOT "%JENA_HOME%" == "" goto :okHome
echo JENA_HOME not set
exit /B

:okHome
set JENA_CP=%JENA_HOME%\lib\*;
set LOGGING=file:%JENA_HOME%\log4j2.properties

echo %LOGGING%

@rem JVM_ARGS comes from the environment.
java %JVM_ARGS% -Dlog4j.configurationFile="%LOGGING%" -cp "%JENA_CP%" arq.sparql %*
exit /B

--------------------------------------------------------------------------------------

PS C:\jena> bat\sparql.bat --version
file:C:\jena\log4j2.properties
ERROR StatusLogger Reconfiguration failed: No configuration found for '2a139a55' at 'null' in 'null'
Jena:       VERSION: 4.8.0
Jena:       BUILD_DATE: 2023-04-20T08:38:51Z

--------------------------------------------------

<img width="566" alt="image" src="https://github.com/apache/jena/assets/41237767/83f6b368-e134-4464-9bcc-c6c0835b919b">

**Comment by larisa1995** [comment]
Dear @afs 

Setting _LOGGING=%JENA_HOME%\log4j2.properties_ helped. Thank you.
