### ISSUE TITLE
Deprecate API operations that may be affected by Jena5.

### ISSUE THREAD

**Issue by afs** [apache/jena#1948]
### Version

4.8.0

### Feature

This is preparation for Jena5 changes by deprecating API calls to features that are "at risk". (Direct use of LiteralLabels, the "well formed" or "isXML" special case for literals).

Discussion also on dev@.

### Are you interested in contributing a solution yourself?

Yes

**Comment by cdekok** [comment]
What is the alternative API to use? it's marked as deprecated but no alternative seems to be provided as Node_Literal has a private constructor?

**Comment by afs** [comment]
Which operation are you referring to? What is the caller trying to do?

NodeFactory is the preferred way to create nodes.

**Comment by cdekok** [comment]
I have a literlabe from the literlalfactory, but with this change i can't convert it to a node anymore which is a bit weird.
I can do a workaround with the NodeFactory but IMO then the LiteralLabelFactory has little use.

**Comment by afs** [comment]
Interesting. 

I have been looking at the Node area to see what can be simplified. Some generality is not used anywhere and has not come up on the mailing list of StackOverflow. I doubt it'll make a significant impact to be simpler, maybe a little extra performance because of less indirections for some processing intense code, and maybe a bit of space saving at scale.

Node_Literal and LiteralLabel, especially in the light of the new term-centric graphs, are a area. I really do wonder what the significant of LiteralLabel is and I was wondering if LiteralLabel could be pulled up into Node_Literal. There is an impact on the `RDFDataype.isEqual` operation -- which should really be called "sameValueAs" because "equal" has multiple meanings (java .equals, sameTermAs sameValueAs).

What are you using LiteralLabel for? Is Node_Literal not teh right concept for the usage?

**Comment by cdekok** [comment]
Currently I have some code that is writing code to RDF, so for example.

```kotlin
val value = LiteralLabelFactory.createTypedLiteral(true)
val node = NodeFactory.createLiteral(label)
```

Now this can be converted ofcourse to just using the NodeFactory e.g

```
NodeFactory.createLiteralByValue(true, XSDDatatype.XSDboolean)
```

It would be nice if the doc block would point to a use method when marking methods as deprecated.

Currently the method `NodeFactory.createLiteral` is marked as deprecated, but the `LiteralLabelFactory` is not only it's not possible to convert a LiteralLabel to a Node anymore since Node_Literal constructor is private.

The intention of the deprecated is a bit unclear for me, what incorrect states should it prevent, and why can I create LiteralLabels but not turn them into nodes?

**Comment by afs** [comment]
A lot of this is legacy (in relation to RDF 1.0), and reasons can be lost in the lost in the mists of time.

I don't see the point of LiteralLabel from the viewpoint of today's Jena. As an interface, it has one implementation. It's in teh `impl` package but has leaked. Maybe the possibility was for complex values was there, but that does not make sense in a SPARQL world.

`NodeFactory.createLiteralByValue` is the operation to use.
