### ISSUE TITLE
Triple-quoted strings ending with quote aren't parsed by riot

### ISSUE THREAD

**Issue by atextor** [apache/jena#1956]
### Version

4.9.0

### What happened?

The following turtle input can not be parsed by riot:

```turtle
@prefix : <http://example.com/> .
:foo :bar """A word is "quoted"""" .
```

```shell
$ riot --sink test.ttl 
06:23:56 ERROR riot            :: [line: 3, col: 1 ] Broken token (newline):  .
```

My understanding is that the last three quotes should be the closing token of the triple-quoted string. If I insert any other character, e.g. a space, after the closing quote of the quoted word, parsing works:

```turtle
@prefix : <http://example.com/> . 
:foo :bar """A word is "quoted" """ .
```

```shell
$ riot --sink test.ttl 
$
```

### Are you interested in making a pull request?

Maybe

**Comment by afs** [comment]
The close is the first 3 consecutive quotes encountered after the opening `"""`  like `"""A word is "quoted""" "`.

https://www.w3.org/TR/turtle/#grammar-production-STRING_LITERAL_LONG_QUOTE

```
STRING_LITERAL_LONG_QUOTE	::=	'"""' (('"' | '""')? ([^"\] | ECHAR | UCHAR )))* '"""'
```

Note the inner `('"' | '""')?` -- three in a row is not covered by the string contents part.

**Comment by atextor** [comment]
The string can contain one quote - which is allowed by the rule - but it must then be followed by some non-quote ECHAR or UCHAR. So that means unescaped quotes are allowed everywhere in a triple-quoted string (which is why I expected this to work) _except_ as the last character, presumably to make parsing easier.

Thanks for the clarification. Since it's obviously not a bug in Jena, I'll close the issue.
