### ISSUE TITLE
fuseki server service is usually interrupted suddenly

### ISSUE THREAD

**Issue by Joey-la** [apache/jena#1972]
### Version

3.16.0

### Question

I installed the jena fuseki 3.16.0 on linux server.  the fuseki service is on running, but automatically disconnected suddenly, usually.

**Comment by kinow** [comment]
There might be something useful in the logs, but 3.16.0 is very old, so it is hard for others to help you troubleshooting it.

**Comment by afs** [comment]
Hi @Joey-la The logs will show what was happening in the server at the time.

I don't recall a specific issue between 3.16.0 and the current release 4.9.0 that matches your description.  If you could say some more about the environment, the server configuration and what is being disconnected, we may be able to help.

**Comment by afs** [comment]
Hi @Joey-la - did you solve this?

**Comment by afs** [comment]
Hi @Joey-la - any update?

There isn't enough information to attempt to reproducible this report. We'll close this if there is no further information.
