### ISSUE TITLE
Is there possible duplicated triples in TDB2?

### ISSUE THREAD

**Issue by xilixii** [apache/jena#1976]
### Version

4.8.0

### Question

I want to know whether TDB will contain two same triples or the loaded triples had been deduplicated when it build the TDB database.

**Comment by afs** [comment]
An RDF graph is a set of triples - there are no duplicates in a graph.

A triple can be in several graphs. If you use the union default graph feature (make the default graph for query be the union of all the named graphs), there will still only be one triple in the default graph.

**Comment by xilixii** [comment]
Thanks @afs
