### ISSUE TITLE
[question] unexpected ConcurrentModificationException while working with GraphMem

### ISSUE THREAD

**Issue by sszuev** [apache/jena#1992]
### Version

4.9.0

### Question

`GraphMem` does not guarantee that the iterator will not be broken if it is interrupted by a modification operation.
So this is just a question.

But in some scenarios when we do so we may expect that it will not be broken if search pattern and concrete triple do not match.

In any case, I think that additional documentation would not hurt.

See:
```java
import org.apache.jena.graph.Graph;
import org.apache.jena.graph.GraphMemFactory;
import org.apache.jena.graph.Node;
import org.apache.jena.graph.NodeFactory;
import org.apache.jena.graph.Triple;
import org.apache.jena.vocabulary.OWL;
import org.apache.jena.vocabulary.RDF;

import java.util.Iterator;

public class TmpGraphMem {

    public static void main(String... args) {
        Graph graph = GraphMemFactory.createGraphMem2();
        for (int i = 0; i < 42; i++) {
            graph.add(Triple.create(NodeFactory.createURI("a" + i), RDF.type.asNode(), OWL.Class.asNode()));
        }

        Triple pattern = Triple.create(Node.ANY, RDF.type.asNode(), OWL.Class.asNode());
        Triple triple1 = Triple.create(NodeFactory.createURI("x"), NodeFactory.createURI("p"), NodeFactory.createURI("W"));
        Triple triple2 = Triple.create(NodeFactory.createURI("x"), NodeFactory.createURI("p"), OWL.Class.asNode());
        System.out.println(pattern.matches(triple1)); // false
        System.out.println(pattern.matches(triple2)); // false

        Iterator<Triple> it = graph.find(pattern);
        it.next();
        it.next();

        graph.add(triple1);
        it.next(); // no ConcurrentModificationException
        it.next(); // no ConcurrentModificationException

        graph.add(triple2);

        it.next(); // ConcurrentModificationException
        it.next(); // ConcurrentModificationException
    }
}
```

**Comment by afs** [comment]
This is standard Java iterator behaviour.

Any modification to an underlying datastructure may invalidate an iterator.

Filtering is not a factor - the filter is navigation of the underlying datastructure.

The same is true for JDK lists and maps.

For example, in a HashMap, the whole hash vector maybe resized, moving everything around.

If you want isolation, consume the iterator to a list and iterate on the list, or keep a record of the changes to make and make them afterwards.

**Comment by sszuev** [comment]
Sure, that's standard for non-concurrent collection. No doubt. 
But thank you for detailed explanation.

I know about isolation and `close`, but thank you anyway.

But I think user may not know that GraphMem behaves just like JDK.
Also, it is strange that behavior differs in these two scenarios. 

It would be nice to have some words in javadoc that states that inappropriate `find` use MAY lead to `ConcurrentModificationException` (or may not).

**Comment by afs** [comment]
Contributions welcome.
