### ISSUE TITLE
Is it possible to utilize the RegistryRequestModifier to send AWS headers to Neptune?

### ISSUE THREAD

**Issue by magutierrm** [apache/jena#1993]
### Version

4.9.0

### Question
Hello,
Starting from version 4.3.0, `java.net.HttpClient` is used as the HTTP client instead of `org.apache.http.client`. Previously, if you wanted to sign your requests, you could intercept them and add the signed HTTP headers using methods provided by the Apache HTTP client.
However, with `java.net.HttpClient`, there is no straightforward way to achieve this. Is it possible to accomplish this using `org.apache.jena.http.sys.RegistryRequestModifier`?
I am doing something like this:
```java
        Map<String, String> signedHeaders = getAwsHeaders();
        HttpRequestModifier modifier = (params, headers) -> headers.putAll(signedHeaders);
        RegistryRequestModifier.get().addPrefix("https://my-neptune-cluster.neptune.amazonaws.com:8182", modifier);
```
However, when I check the logs of my requests, I don't see any headers added.

Thank you in advance.

**Comment by afs** [comment]
Try "add" not "addPrefix"

Your example throws "IllegalArgumentException" (because prefix does not end in "/").

**Comment by magutierrm** [comment]
@afs Thanks for the answer. Unfortunately, I also tried with `add` but it did not work.
Is there any place where `RDFConnectionRemoteBuilder` should call `RegistryRequestModifier`? Maybe I am calling it in a wrong place

**Comment by afs** [comment]
Were you getting IllegalArgumentException? If not, then maybe the code isn't called.

You can use `addPrefix("https://my-neptune-cluster.neptune.amazonaws.com:8182/")` -- ends in "/" and applies to any URL at that host over https.

The registry is system-wide.

To test, use:

```
                HttpRequestModifier modifier = (params, headers) -> {
                    System.err.println("CALLED");
                    };
                RegistryRequestModifier.get().add(....., modifier);
```

and see what client-side output your get.

After that, please provide a complete, minimal example. It does not have to be "amazonaws.com".

**Comment by magutierrm** [comment]
Is not being called, Not sure if I am doing something wrong
```java
@Slf4j
@Component
public class Test {

    @PostConstruct
    public void init() throws InterruptedException, IOException {

        HttpRequestModifier modifier = (params, headers) -> {
            System.err.println("CALLED");
            headers.put("x-test", "test");
        };
        RegistryRequestModifier.get().addPrefix("https://github.com/status/", modifier);

        HttpClient httpClient = HttpClient.newBuilder().build();
        HttpResponse<String> response = httpClient.send(
            HttpRequest.newBuilder()
                       .GET()
                       .uri(URI.create("https://github.com/status/"))
                       .build(),
            HttpResponse.BodyHandlers.ofString()
        );

        log.info("Request {}", response.request());
        log.info("Response {}", response);
        log.info("Headers {}", response.request().headers().map());
    }

}
```

Logs:
```
2023-08-17 12:07:52.810 - INFO 25359 --- [           main] com.xxx.xxx.neptune.config.Test      : Request https://github.com/status/ GET
2023-08-17 12:07:52.811 - INFO 25359 --- [           main] com.xxx.xxx.neptune.config.Test      : Response (GET https://github.com/status/) 200
2023-08-17 12:07:52.811 - INFO 25359 --- [           main] com.xxx.xxx.neptune.config.Test      : Headers {}
```

**Comment by afs** [comment]
> `HttpClient httpClient = HttpClient.newBuilder().build();`
> `       HttpResponse<String> response = httpClient.send(`

There isn't any Jena code there : `RegistryRequestModifier` is a Jena feature.

Example:
```java
        HttpRequestModifier modifier = (params, headers) -> {
            System.err.println("CALLED");
            //headers.put("x-test", "test");
        };

        String URL = "https://github.com/status/";
        RegistryRequestModifier.get().addPrefix(URL, modifier);

        try {
            RDFConnection conn = RDFConnectionRemote.service("https://github.com/status")
                    .queryEndpoint("query")
                    .build();
            conn.query("ASK{}").execAsk();
        } catch (QueryExceptionHTTP ex) {
            if ( 404 != ex.getStatusCode() )
                System.err.print("Expected status code 404. Got "+ex.getStatusCode());
        }

        System.out.println("DONE");
        System.exit(0);

```
It only seems to work for query and update, not GSP/DSP which probably is a bug.

What operations are your trying to use?

**Comment by magutierrm** [comment]
@afs Thanks for this code snippet. I didn't know that we can directly add our service without having to pass an HTTP Client. This works properly 😄 May I ask why you have decided to use the `http.net.java.HttpClient`? In my opinion, it is a very restricted client. In any case, you can close the issue. 
Thank you again
