### ISSUE TITLE
Inconsistent Labeling for Blank Nodes Across Writers

### ISSUE THREAD

**Issue by aliariff** [apache/jena#1997]
### Version

4.9.0

### What happened?

There's an observed inconsistency in how blank nodes are labelled across different writer classes. The `RowSetWriterCSV` class labels blank nodes using the `NodeToLabelMap`. However, the `RowSetWriterJSON` and `RowSetWriterXML` writers decide on the labelling strategy based on the provided context:

```java
boolean outputGraphBNodeLabels = (context != null) && context.isTrue(ARQ.outputGraphBNodeLabels);
labels = outputGraphBNodeLabels
    ? SyntaxLabels.createNodeToLabelAsGiven()
    : SyntaxLabels.createNodeToLabel();
```

For consistency across output formats, it's suggested to handle blank node labelling the same way across all writers. Specifically, the CSV writer should also decide the labelling strategy based on context, as in the JSON and XML writers.

### Are you interested in making a pull request?

Yes

**Comment by afs** [comment]
Hi @aliariff - could you show a concrete example and say why it matters to you?

Especially for the CSV format, which is lossy anyway, it uses the `_:bN` form for brevity of display.

TSV preserves more of the RDF-ness like strings vs URIs.

Blank nodes in the results format are scoped to the result document - they don't represent the original blank node in the data. (That's a feature of blank nodes.)

**Comment by afs** [comment]
That is relying on a Jena-specific feature.

By the standards, blank nodes in the results format are scoped to the result document, not across documents.

Bug label removed - this is a feature request.

If you want to add an opt-in form of labels for CSV, then please do so.
