### ISSUE TITLE
Fuseki webui ability to host under a path with env

### ISSUE THREAD

**Issue by Rulqu** [apache/jena#2018]
### Version

4.9.0

### Feature

Add env for vite to build the files with a path. For example I'd like to be able to build the webui like this:
`VITE_PUBLIC_PATH=/fuseki/ yarn build` and then it can be hosted under /fuseki/ path.

I've fixed this myself for my needs but I don't know if this is good enough for a pull request.
```
diff --git a/jena-fuseki2/jena-fuseki-ui/vite.config.js b/jena-fuseki2/jena-fuseki-ui/vite.config.js
index 612de16ad8..07ed9db898 100644
--- a/jena-fuseki2/jena-fuseki-ui/vite.config.js
+++ b/jena-fuseki2/jena-fuseki-ui/vite.config.js
@@ -15,13 +15,16 @@
  * limitations under the License.
  */
 
-import { defineConfig } from 'vite'
+import { defineConfig, loadEnv } from 'vite'
 import vue from '@vitejs/plugin-vue'
 import istanbul from "vite-plugin-istanbul";
 const path = require("path")
 
 // https://vitejs.dev/config/
-export default defineConfig({
+export default defineConfig(({ command, mode }) => {
+  const env = loadEnv(mode, process.cwd(), '')
+  return {
+    base: env.VITE_PUBLIC_PATH || '/',
     plugins: [
       vue(),
       istanbul({
@@ -116,4 +119,5 @@ export default defineConfig({
         }
       },
     }
+  }
 })
```

### Are you interested in contributing a solution yourself?

Yes

**Comment by kinow** [comment]
Hi @Rulqu ,

Thanks for the detailed issue description.

`yarn build` calls `vite build`. So maybe you can try changing the parameters (or calling vite directly via `vite build` or `npx vite build`) and use the `--base` parameter.

https://vitejs.dev/guide/build.html#public-base-path

![image](https://github.com/apache/jena/assets/304786/56a8c711-c0cd-4e4a-ac34-72b58b83b582)

**Comment by Rulqu** [comment]
I've already fixed this for my own needs but I wanted to provide an improvement that could help someone in the future. This method would also allow the usage of different environment files per vite mode (production vs staging).
