### ISSUE TITLE
Jena5 Node Changes

### ISSUE THREAD

**Issue by afs** [apache/jena#2020]
Changes to Node and related classes (RDF Terms)

* Simplify type hierarchy
* `LiteralLabel`:
  * Convert to class
  * Restrict use to Node implementation.
  * Make it terms centric.
  * Eager and lazy forms for value calculation
* Remove BlankNodeId redirection in Node_Blank
* Remove partial, incomplete RDF 1.0 support

**Comment by arne-bdt** [comment]
In the Jena5 branch `org.apache.jena.graph.impl.LiteralLabel#valueMode` seems to be fixed to `EAGER`. 
Did I miss something or are you planning to initialize it via `org.apache.jena.shared.impl.JenaParameters#enableEagerLiteralValidation` in the future?
Or possibly replace it completely by `enableEagerLiteralValidation` since there is only one usage of `valueMode`?

**Comment by afs** [comment]
`LiteralLabel.valueMode` should be "lazy" but as the comment says, further work is needed on the test suite. Looks like it got left in "safe" mode. 

The idea is that if the value isn't needed it isn't calculated. This happens on the parser path including database loading.
Model API use passing in a value is "eager" by nature. #2050.

`JenaParameters#enableEagerLiteralValidation` is only controlling whether exceptions are thrown or ill-formed literals are allowed. It ought to be be removed and the default behaviour (false) be the only behaviour.

In RDF 1.0, the position of the standard was more that ill-formed literals made everything illegal. But that means a processor must have an understanding of all datatypes including custom ones.

 In RDF 1.1, ill-formed literals are treated as local errors. They cause parser warnings.

Generally, I think `JenaParameters` should go away -- #2049.
I don't have much faith in running with non-default settings.

The OWL related flag can move to somewhere in OntModel code. Ditto the Inf related one.

**Comment by arne-bdt** [comment]
Thank you for the detailed explanation.

So the values would be parsed (lazy initialised) during the SPARQL execution for filters and aggregates, for example?

**Comment by afs** [comment]
SPARQL execution has it's own value system.

The ModelAPI and the code in LiteralLabel backing that up, is about mapping some java types.

SPARQL is XSD related, it has wider coverage, no direct java mapping, and has to comply with XQuery/XPath Functions and Operators evaluation.

**Comment by afs** [comment]
It is probably better to raise specific issues for Node evolution.

Closing this issue based on #2020.
