### ISSUE TITLE
Jena5 Model API changes

### ISSUE THREAD

**Issue by afs** [apache/jena#2021]
* Remove deprecated classes and methods
* Remove unused code: 
* Simplify container iterators
* Remove reification support
* Remove isXML/isWellFormed from APIs
* Remove "ModelExtract" - `TripleBoundary`, `StatementBoundary`, `GraphExtract`, `ModelExtract`
* Remove `RDFReaderF.getReader()` and `RDFWriter.getWriter()`
* Remove `ResourceF`
* Remove `Selector` and `Model.query(Selector)`

**Comment by namedgraph** [comment]
Why remove `isXML`?

**Comment by afs** [comment]
Whatever you think it means, it doesn't! It is closer to "well formed" because it applies to more than `rdf:XMLLiteral`.

It's a left-over from RDF 1.0. `rdf:XMLLiteral` had a special place in RDF 1.0.

RDF 1.1 defines rdf:XMLLiteral like any other datatype. RDF 1.1 is tolerant of ill-formed literals and treats them as RDF terms without values.

**Comment by afs** [comment]
Closed by #2029.
