### ISSUE TITLE
RRX: New RDF/XML parser

### ISSUE THREAD

**Issue by afs** [apache/jena#2025]
The RRX parser replaces ARP as the default choice of RDF/XML parser in RIOT.

RRX is specially for parsing RDF/XML files, not general RDF/XML processing. It is more maintainable.

The ARP code remains in the code base with special `Lang` constants.

**Comment by arne-bdt** [comment]
Wow! In some of my benchmarks, the speed of parsing RDF/XML almost doubled.
Thanks a lot!

**Comment by afs** [comment]
It is interesting that the SAX version is so much faster than the near-identical StAX variants of RRX. There must be a smal number of Java objects created internally to give the easier to use StAX APIs.

**Comment by afs** [comment]
Closed by #2029.
