### ISSUE TITLE
Deprecate use of initial binding

### ISSUE THREAD

**Issue by afs** [apache/jena#2028]
"InitialBinding" is only available in some query/update execution - it is not available for remote execution.

It is replaced by "substitution" which is rewriting the query or update within the caller client. This can be applied to any query/update executions, including remote calls.

**Comment by afs** [comment]
Closed by #2029.

**Comment by namedgraph** [comment]
@afs what is the substitution API? Adding a `VALUES` block?

**Comment by afs** [comment]
The execution building have a `substitute`.

83241740ba31
