### ISSUE TITLE
Incorporate the rdf-tables and expiring-map code in Jena GeoSPARQL.

### ISSUE THREAD

**Issue by afs** [apache/jena#2036]
Jena's GeoSPARQL support relies on two Apache-licensed packages [rdf-tables](https://github.com/galbiston/rdf-tables) and [expiring-map](https://github.com/galbiston/expiring-map).

These package were last released Jan 29, 2019

galbiston has done a fantastic job on GeoSPARQL.

Some of the Jena5 changes (TDB1 renames) impact these packages and dependency version differences have "just happened to work".

It seems safer to incorporate the code from these two packages into Jena's codebase so that they track Jena.

Put under `org.apache.jena.ext.io.github.galbiston....` which makes it easily reversible.

(The expiring map can probably be replaced by a Caffeine cache with entry expiry.)

**Comment by rvesse** [comment]
If we're pulling the `rdf-tables` library in could we modify it to use Caffeine instead of `expiring-map` as the latter looks to be a minimal subset of functionality we already get from Caffeine?

**Comment by afs** [comment]
@rvesse  Yes, I think we could.

**Comment by afs** [comment]
Closed by #2029.

**Comment by afs** [comment]
Issue #2048 is for replacing ExpiringMap with a Caffeine based cache.
