### ISSUE TITLE
[jena5] upgrade UI deps

### ISSUE THREAD

**Issue by kinow** [apache/jena#2054]
### Change

Placeholder issue for upcoming PR

### Are you interested in contributing a pull request for this task?

Yes

**Comment by afs** [comment]
The build failure seems to be: 
```
[INFO] --- frontend:1.14.2:yarn (yarn install) @ jena-fuseki-ui ---
[INFO] Running 'yarn install --frozen-lockfile' in /home/jenkins/workspace/Jena/Jena_Development_Test/jena-fuseki2/jena-fuseki-ui
[INFO] node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)
```
so not a Jena build issue.

Looks like:
https://stackoverflow.com/questions/72921215/getting-glibc-2-28-not-found

**Comment by afs** [comment]
Te build situation has already been reported: https://issues.apache.org/jira/browse/INFRA-23954

The issue is `nanoid` 5.* 
```
[INFO] error nanoid@5.0.2: The engine "node" is incompatible with this module. Expected version "^18 || >=20". Got "16.20.2"
```
It is a nanoid v4->v5 change.

Maybe we can use nanoid v4.0.2.

**Comment by afs** [comment]
We have some overrides:
```
  "overrides": {
    "terser": "^5.14.2",
    "loader-utils": "^1.4.2",
    "cookiejar": "^2.1.4",
    "json5": "^1.0.2"
  }
```
Are these still necessary?

**Comment by kinow** [comment]
>It is a nanoid v4->v5 change.
>
>Maybe we can use nanoid v4.0.2.

Not sure, haven't seen that error before -- I always use GH Actions to test Node apps, where I just say

```yaml
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: yarn
```

>We have some overrides:
>Are these still necessary?

Hard to say. The overrides are handy as they solve dependency issues like the ones we had with security, but at the cost that later you need to inspect the dependency tree with the resolution, check NPM for releases, modify your `package.json`, check the dependency tree again, and confirm that the override can be removed.

Created https://github.com/apache/jena/issues/2082 to track that :+1: 

Thanks!
