### ISSUE TITLE
Better support for JSON-LD Titanium development?

### ISSUE THREAD

**Issue by jakubklimek** [apache/jena#2128]
### Version

4.10.0

### Question

Since Apache Jena chose to use Titanium as the JSON-LD 1.1 implementation, would it be possible to somehow allocate some resources to its development, supporting @filip26? There are issues (https://github.com/filip26/titanium-json-ld/issues/292, https://github.com/filip26/titanium-json-ld/issues/248 and others) preventing proper use of JSON-LD 1.1 in our use cases, and therefore, the use of Apache Jena itself, and it seems that these issues have no priority, probably due to lack of resources.

**Comment by kinow** [comment]
>would it be possible to somehow allocate some resources to its development

I am not sure if we have resources to allocate here. We are all volunteers, some contributors work actively with Jena, so they may have some extra $time to work on features required by employers.

>There are issues (https://github.com/filip26/titanium-json-ld/issues/292, https://github.com/filip26/titanium-json-ld/issues/248 and others) preventing proper use of JSON-LD 1.1 in our use cases, and therefore, the use of Apache Jena itself, and it seems that these issues have no priority, probably due to lack of resources.

If you need that for a project, or for your $work, the best option here could be to hire someone to work on those issues, or maybe try to improve titanium-json-ld.

For me my main use cases involve the Fuseki UI, loading and querying simple ontologies, so I use my spare/volunteer time to focus on these areas. At $work I have very little use of Jena, so my bandwidth to work on Jena is limited -- other contributors/volunteers here might have similar situations.

**Comment by filip26** [comment]
@jakubklimek Thank you for seeking support for Titanium! I was not aware of this.

The fastest way to speed up development is to contribute, to spend your own time. Or if it is not an option for you, then you can become a sponsor or hire some as has been mentioned above.

As for any other open-source project,  contribution is voluntary, and this applies to developers as well as to [commercial]users.

**Comment by afs** [comment]
Closing question.
