### ISSUE TITLE
Fuseki-server fails to start when using the drop in jar for service-enhancer

### ISSUE THREAD

**Issue by OyvindLGjesdal** [apache/jena#2161]
### Version

4.10.0

### What happened?

The artefact downloaded from maven for the service enhancer return class not found, when dropped into the extra folder.

This happens when running fuseki as a service, and loading the service enhancer from a  configuration file, while downloading the 4.10.0 ServiceEnhancer artefact from maven.

Is it the order of the class loading?

I see guava was added for use not that long ago, would it make sense to add the dependency to the service-enhancer pom.xml? to ensure that it is loaded, or could it be that it is my user error?

from the docs:
> The SE plugin can be manually built or downloaded from maven central (it is self-contained without transitive dependencies). Placing it into the run/extra folder makes it available for use with Fuseki. The plugin and Fuseki versions should match.

Command used to startup fuseki:

```
/opt/fuseki/fuseki-server
```

### Relevant output and stacktrace

```log
Jan 05 11:12:01 server fuseki-server[92517]: Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder
Jan 05 11:12:01 server fuseki-server[92517]:         at org.apache.jena.sparql.service.enhancer.impl.ServiceResponseCache.<init>(ServiceResponseCache.java:59)
Jan 05 11:12:01 server fuseki-server[92517]:         at org.apache.jena.sparql.service.enhancer.impl.ServiceResponseCache.<init>(ServiceResponseCache.java:53)
Jan 05 11:12:01 server fuseki-server[92517]:         at org.apache.jena.sparql.service.enhancer.init.ServiceEnhancerInit.init(ServiceEnhancerInit.java:90)
Jan 05 11:12:01 server fuseki-server[92517]:         at org.apache.jena.sparql.service.enhancer.init.ServiceEnhancerInit.start(ServiceEnhancerInit.java:81)
Jan 05 11:12:01 server fuseki-server[92517]:         at org.apache.jena.base.module.Subsystem.lambda$initialize$1(Subsystem.java:117)
Jan 05 11:12:01 server fuseki-server[92517]:         at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Jan 05 11:12:01 server fuseki-server[92517]:         at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:193)
Jan 05 11:12:01 server fuseki-server[92517]:         at org.apache.jena.base.module.Subsystem.forEach(Subsystem.java:169)
Jan 05 11:12:01 server fuseki-server[92517]:         at org.apache.jena.base.module.Subsystem.initialize(Subsystem.java:115)
Jan 05 11:12:01 server fuseki-server[92517]:         at org.apache.jena.sys.JenaSystem.init(JenaSystem.java:89)
Jan 05 11:12:01 server fuseki-server[92517]:         at arq.cmdline.CmdARQ.<clinit>(CmdARQ.java:29)
Jan 05 11:12:01 server fuseki-server[92517]:         at org.apache.jena.fuseki.cmd.FusekiCmd.main(FusekiCmd.java:65)
Jan 05 11:12:01 server fuseki-server[92517]: Caused by: java.lang.ClassNotFoundException: com.google.common.cache.CacheBuilder
Jan 05 11:12:01 server fuseki-server[92517]:         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
Jan 05 11:12:01 server fuseki-server[92517]:         at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
Jan 05 11:12:01 server fuseki-server[92517]:         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
Jan 05 11:12:01 server fuseki-server[92517]:         ... 12 more
```

### Are you interested in making a pull request?

None

**Comment by rvesse** [comment]
>  I see guava was added for use not that long ago, would it make sense to add the dependency to the service-enhancer pom.xml? to ensure that it is loaded, or could it be that it is my user error?

I thought actually the opposite was true, Guava was removed in favour of [ben-manes/caffeine](https://github.com/ben-manes/caffeine) since we were only really using Guava for caching and the lack of stability in Guava APIs meant we were having to mess around with shading which we no longer wanted to do.

So this might be a side-effect of that, the service enhancer plugin previously assumed that it would get Guava transitively from elsewhere in Jena which is no longer true.

So yes probably two options:

- Short term - explicitly add Guava as a local dependency to your Fuseki Classpath
- Long term - create a new issue and PR to migrate the plugin to using the new preferred cache APIs

**Comment by afs** [comment]
Google Guava also has dependencies:
```
[INFO] +- com.google.guava:guava:jar:32.1.3-jre:compile
[INFO] |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  \- com.google.j2objc:j2objc-annotations:jar:2.8:compile
```

**Comment by OyvindLGjesdal** [comment]
https://github.com/apache/jena/blob/jena-4.10.0/jena-extras/jena-serviceenhancer/pom.xml#L103
It seems the artefact published doesn't use the profile bundle.

```
  <!-- Profile to build a "plugin jar bundle" that can be loaded with fuseki or any other jena-based app -->
  <profiles>
    <profile>
      <id>bundle</id>
      <dependencies>
        <dependency>
          <groupId>org.apache.jena</groupId>
          <artifactId>jena-arq</artifactId>
          <version>4.10.0</version>
          <scope>provided</scope>
        </dependency>
      </dependencies>
```

When I actived the profile (by setting activeByDefault true) and built the outputs, the jar is a 3 MB vs 207 KB. Will check if it launches tomorrow.

Outputs of build at 4.10 with profile active:
```
drwxr-xr-x@ 14    448B Jan  9 21:40 .
drwxr-xr-x@  7    224B Jan  9 21:41 ..
-rw-r--r--@  1     30B Jan  9 21:39 .plxarc
drwxr-xr-x@  4    128B Jan  9 21:39 classes
drwxr-xr-x@  3     96B Jan  9 21:39 generated-sources
drwxr-xr-x@  3     96B Jan  9 21:39 generated-test-sources
-rw-r--r--@  1    165K Jan  9 21:40 jena-serviceenhancer-4.10.0-sources.jar
-rw-r--r--@  1    3.1M Jan  9 21:40 jena-serviceenhancer-4.10.0.jar
drwxr-xr-x@  3     96B Jan  9 21:40 maven-archiver
drwxr-xr-x@  3     96B Jan  9 21:39 maven-shared-archive-resources
drwxr-xr-x@  3     96B Jan  9 21:39 maven-status
-rw-r--r--@  1    207K Jan  9 21:40 original-jena-serviceenhancer-4.10.0.jar
drwxr-xr-x@ 16    512B Jan  9 21:40 surefire-reports
drwxr-xr-x@  6    192B Jan  9 21:39 test-classes
```

**Comment by OyvindLGjesdal** [comment]
It starts up when dropped in, but the first example in the docs using wikidata fails with a timeout.

It looks like a different bug, either in the example, or in the rewriting, where the ?s values aren't injected. 

If the VALUES clause are moved into the service, there is a cache result.

The example from the docs:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
SELECT ?s ?l {
  # The ids below correspond in order to: Apache Jena, Semantic Web, RDF, SPARQL, Andy Seaborne
  VALUES ?s { wd:Q1686799 wd:Q54837 wd:Q54872 wd:Q54871 wd:Q108379795 }
 
  SERVICE <cache:loop:bulk+5:https://query.wikidata.org/sparql> {
    SELECT ?l {
      ?s rdfs:label ?l
      FILTER(langMatches(lang(?l), 'en'))
    } ORDER BY ?l LIMIT 1
  }
}
```

from the logs:

```10:18:10 INFO  Fuseki          :: [3] Query =
Jan 10 10:18:10 server fuseki-server[98423]: PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
Jan 10 10:18:10 server fuseki-server[98423]: PREFIX wd: <http://www.wikidata.org/entity/>
Jan 10 10:18:10 server fuseki-server[98423]: SELECT ?s ?l {
Jan 10 10:18:10 server fuseki-server[98423]:   # The ids below correspond in order to: Apache Jena, Semantic Web, RDF, SPARQL, Andy Seaborne
Jan 10 10:18:10 server fuseki-server[98423]:   VALUES ?s { wd:Q1686799 wd:Q54837 wd:Q54872 wd:Q54871 wd:Q108379795 }
Jan 10 10:18:10 server fuseki-server[98423]:
Jan 10 10:18:10 server fuseki-server[98423]:   SERVICE <cache:loop:bulk+5:https://query.wikidata.org/sparql> {
Jan 10 10:18:10 server fuseki-server[98423]:     SELECT ?l {
Jan 10 10:18:10 server fuseki-server[98423]:       ?s rdfs:label ?l
Jan 10 10:18:10 server fuseki-server[98423]:       FILTER(langMatches(lang(?l), 'en'))
Jan 10 10:18:10 server fuseki-server[98423]:     } ORDER BY ?l LIMIT 1
Jan 10 10:18:10 server fuseki-server[98423]:   }
Jan 10 10:18:10 server fuseki-server[98423]: }
Jan 10 10:18:10 server fuseki-server[98423]: 10:18:10 INFO  QueryIterServiceBulk :: Schedule for current batch:
Jan 10 10:18:10 server fuseki-server[98423]: 10:18:10 INFO  QueryIterServiceBulk :: input 0: [[0..1)=fetch]
Jan 10 10:18:10 server fuseki-server[98423]: 10:18:10 INFO  BatchQueryRewriter :: Rewritten bulk query: SELECT  *
Jan 10 10:18:10 server fuseki-server[98423]: WHERE
Jan 10 10:18:10 server fuseki-server[98423]:   {   { { SELECT  ?l
Jan 10 10:18:10 server fuseki-server[98423]:           WHERE
Jan 10 10:18:10 server fuseki-server[98423]:             { ?s  <http://www.w3.org/2000/01/rdf-schema#label>  ?l
Jan 10 10:18:10 server fuseki-server[98423]:               FILTER langMatches(lang(?l), "en")
Jan 10 10:18:10 server fuseki-server[98423]:             }
Jan 10 10:18:10 server fuseki-server[98423]:           ORDER BY ?l
Jan 10 10:18:10 server fuseki-server[98423]:           LIMIT   1
Jan 10 10:18:10 server fuseki-server[98423]:         }
Jan 10 10:18:10 server fuseki-server[98423]:         BIND(0 AS ?__idx__)
Jan 10 10:18:10 server fuseki-server[98423]:       }
Jan 10 10:18:10 server fuseki-server[98423]:     UNION
Jan 10 10:18:10 server fuseki-server[98423]:       { BIND(1000000000 AS ?__idx__) }
```

<img width="1915" alt="fetching-data-failed" src="https://github.com/apache/jena/assets/5328572/c49efd80-0f35-4ace-b3b1-cc4bc4f3ef6b">

**Comment by Aklakan** [comment]
> * Long term - create a new issue and PR to migrate the plugin to using the new preferred cache APIs

I did a quick check for what parts of guava my service enhancer code uses - and its only the cache.
The caffeine cache is transitively provided by arq via atlas - so migrating the service enhancer plugin to caffeine should restore "drop-in" functionality. I'll look into it.

**Comment by afs** [comment]
Good idea.

If the Jena cache abstraction works, the choice can be abstracted away.

But the abstraction is basic functionality only without any build control except size.

One reason for switching is to reduce the exposure to Guava which is a big library and Jena only uses some parts of it. When Jena is used as a library, there is a risk of version conflicts with the rest of the application choices. Shading solved that but it means application have two copies of guava (or more - shading the version to get isolation is common).

**Comment by Aklakan** [comment]
Switching the cache to caffeine is doable, but unfortunately for my last post I had only searched for 'guava'.

I noticed my code also relies on `com.google.common.collect.{Range, RangeMap, RangeSet, etc}` for managing the ranges of cached data. This part would be too much effort to replace - at least in the short run.

One way to resolve the dependent jars with maven could be done like this (untested whether only including guava  is sufficient):

```bash
# Fetch the serviceenhancer pom from maven central
mvn dependency:copy -D'artifact=org.apache.jena:jena-serviceenhancer:4.10.0:pom' \
  -Dmdep.stripVersion=true -D'outputDirectory=./target'

# Transitively retrieve dependencies by specific groupId(s)
# Output folder is relative to the given pom
mvn -f './target/jena-serviceenhancer.pom' \
  dependency:copy-dependencies -Dtransitive -D'includeGroupIds=com.google.guava' \
 -DincludeScope=runtime -DoutputDirectory='.'

# Finally copy the downloaded jars to the fuseki extras folder
```

Using -D'excludeGroupIds=org.apache.jena' excludes the artifacts in that group but still downloads their transitive dependencies :weary: 


- Maybe for now its best to just update the documentation that guava is needed in addition (possibly adding download links and/or the maven snippet)?
- Might packaging as a Fuseki module be an option that makes things easier?

**Comment by afs** [comment]
Completed by #2271, #2288 and https://github.com/apache/jena-site/pull/182
