### ISSUE TITLE
Update dependabot to include npm.

### ISSUE THREAD

**Issue by afs** [apache/jena#2172]
### Change

Add a configured `package-ecosystem: "npm"`

### Are you interested in contributing a pull request for this task?

Yes

**Comment by afs** [comment]
@kinow - that was quick! Glad you like it.

We can see how this turns out. It may be overwhelming.

(For the general reader - we already get security dependabot sent to the project.)

**Comment by kinow** [comment]
I just added that to another project and thought about doing that for Jena later!!!

A few minutes after doing that I received a few dependabot pull requests (I had received others to that repository, but somehow having the npm & github-actions packages seem to have helped).

https://github.com/tupilabs/vue-lumino/commit/e76ab43add3269a6e93bee1597380656dd958066

**Comment by afs** [comment]
Well, that got busy for both Java and Javascript!

It'll be catch-up for javascript.

They have "limit 10". The java ones are due to changing "monthly" to "weekly". I'd seen them on other projects so I locally edited pom.xml and ran a build to check them all.

There are configuration options for dependabot:

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups 

Having groups for "patch" and maybe "minor" would help.
