### ISSUE TITLE
NodeTransformLib misses transformation of SERVICE ?var

### ISSUE THREAD

**Issue by Aklakan** [apache/jena#2214]
### Version

5.0.0-SNAPSHOT

### What happened?

The following snippet is supposed to append "XXX" to all variable names.
However, as can be seen from the output, the node transform is not performed on OpService instances, which breaks the query after transform.

The class that would need to be updated is [org.apache.jena.sparql.graph.NodeTransformOp](https://github.com/apache/jena/blob/175212fe91d8dc0956c1998b02725037ab6645a6/jena-arq/src/main/java/org/apache/jena/sparql/graph/NodeTransformOp.java#L45).

```java
public class Test {
    public static void main(String[] args) {
        String queryStr = String.join("\n",
                "SELECT * {",
                "  BIND(<http://dbpedia.org/sparql> AS ?service)",
                "  SERVICE ?service {",
                "    <http://dbpedia.org/resource/RDF_query_language> ?p ?o",
                "  }",
                "}");
        Query beforeQuery = QueryFactory.create(queryStr);
        Op beforeOp = Algebra.compile(beforeQuery);
        Op afterOp = NodeTransformLib.transform(
                n -> n.isVariable() ? Var.alloc(n.getName() + "XXX") : n, beforeOp);
        Query afterQuery = OpAsQuery.asQuery(afterOp);

        System.out.println(afterQuery);
    }
}
```

```sparql
SELECT  *
WHERE
  { BIND(<http://dbpedia.org/sparql> AS ?serviceXXX)
    SERVICE ?service    # <- Transformation was not applied!
      { <https://dbpedia.org/page/RDF_query_language>
                  ?pXXX  ?oXXX}
  }
```

### Are you interested in making a pull request?

Maybe

**Comment by afs** [comment]
Confirmed!

You can use `"""`-strings for Jena5.
