### ISSUE TITLE
LATERAL query evaluation error

### ISSUE THREAD

**Issue by afs** [apache/jena#2218]
### Version

4.10.0, 5.0.0 development

### What happened?

Details https://github.com/w3c/sparql-dev/issues/100#issuecomment-1910692468

Query:
```sparql
PREFIX ex: <http://example.org/>

SELECT ?s ?o WHERE {
    ?s a ex:T.
    OPTIONAL { LATERAL {SELECT ?s ?o WHERE { ?s ex:p ?o } ORDER BY ?o LIMIT 2} }
```

Data:
```turtle
PREFIX ex: <http://example.org/>

ex:s1 a ex:T ;
   ex:p "11" , "12" , "13" .

ex:s2 a ex:T ;
   ex:p "21" , "22" , "23" .

ex:s3 a ex:T .
```
Correct result:
```
----------------
| s     | o    |
================
| ex:s3 |      |
| ex:s1 | "11" |
| ex:s1 | "12" |
| ex:s2 |      |
----------------
```
Wrong result:
```
----------------
| s     | o    |
================
| ex:s3 |      |
| ex:s1 | "11" |
| ex:s1 | "12" |
| ex:s2 | "21" |
| ex:s2 | "22" |
----------------
```

**Comment by kinow** [comment]
Strange, I  would have guess the query would return the wrong result (haven't used a lateral join in a while, last I used was in Postgres to perform like a for-each).

**Comment by afs** [comment]
After staring at the query and execution for _ages_ ... the "wrong" result now looks right to me
It is for completely the wrong reasons though.

Discussion continues on
https://github.com/w3c/sparql-dev/issues/100#issuecomment-1910692468
(this is only part of that issue).

**Comment by afs** [comment]
Re purposing this issue: the lateral implementation generally can improved. The jena4.x implementation makes assumptions about how ARQ executes and these assumptions aren't always valid.
