### ISSUE TITLE
Failing tests org.apache.jena.riot.TestSysRIOT#chooseBaseIRI_3 and org.apache.jena.riot.TestSysRIOT#chooseBaseIRI_4

### ISSUE THREAD

**Issue by arne-bdt** [apache/jena#2232]
### Version

5.0.0-SNAPSHOT

### What happened?

When I run maven dev clean+install on windows, the following tests fail:
- org.apache.jena.riot.TestSysRIOT#chooseBaseIRI_3
- org.apache.jena.riot.TestSysRIOT#chooseBaseIRI_4 

From the assert it seems that SysRIOT.chooseBaseIRI(null, "c:")  should return "file:///c:/" but the return value is "c:"

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
Are you on Windows?

**Comment by afs** [comment]
My bad.
I had a local branch which I'd forgotten to finish.

**Comment by arne-bdt** [comment]
Yes, Windows and this exact problem. 
I couldn't find any mention of the problem in the github topics, so I added one.
Unfortunately, I wasn't able to understand the problem by debugging. 
--> Thank you for solving the problem so quickly! (while I tried and failed again)
