### ISSUE TITLE
Literal.getString() on non-string typed literal does not throw an exception as it should

### ISSUE THREAD

**Issue by BalduinLandolt** [apache/jena#2248]
### Version

4.10.0

### What happened?

on `org.apache.jena.rdf.model.Literal`, the documentation states:

```java
    /**
     * If the literal is interpretable as a string return its value.
     * For typed literals this will throw an error for non string
     * literals and one needs to use getLexicalForm to return the
     * string form of other datatypes.
     *
     * @return the literal string
     */
    public String getString() ;
```

however, when I call `getString()` on a literal that is not a string (e.g. `xsd:float`), I do not get an exception but instead it returns the lexical value. This is obviously in contrast to the javadoc.

I think the code in question is in `package org.apache.jena.rdf.model.impl.LiteralImpl`:

```java
@Override
    public String getString()  {
        return asNode().getLiteralLexicalForm();
    }
```

### Are you interested in making a pull request?

Maybe

**Comment by afs** [comment]
Thanks for the report.

That code has changed in many years (*) so it would seem better to change the javadoc than change the implementation. 

(*) traces back to before the package renaming at Jena2->Jena3 April 2015.

**Comment by BalduinLandolt** [comment]
Fair enough, though changing the code would have been more convenient for me. But it's easy enough to work around, so no problem.

I don't suppose it would be very idiomatic to have another method `getStringOrFail()` (or whatever name would seem fitting), like we see in Scala a lot?

**Comment by BalduinLandolt** [comment]
> @BalduinLandolt so maybe we should have
> 
> ```java
> public Optional<String> getString()
> ```
> 
> ?

I would be happy with that, but from what I understand, @afs does not want to introduce a breaking change on `getString()`, which I suppose this would be, right?

**Comment by afs** [comment]
I thought the mistake probably arose at the RDF 1.0 to RDF 1.1 boundary. 

In RDF 1.0 strings don't have a datatype; in RDF 1.1, they do (xsd:string). That then explains "For typed literals" -- strings are typed literals nowadays.

But its the same code in Jena 2.

Just above `getString`
```
 @Override
    public double getDouble()  {
        if (isPlainLiteral()) {
            return Double.parseDouble(getLexicalForm());
        } else {
            return asNumber(getValue()).doubleValue();
        }
    }
```

Operations like "getDouble" attempt to parse the lexical form `Double.parseDouble(getLexicalForm())`. These operations are not "get if double" despite that being the natural reading (nowadays). So "getString" returning the lexical form is "parse as string".

There is a good case for a redone Model-like API using more modern idioms and expected naming.

Binary compatibility does seem to be appreciated by users.
