### ISSUE TITLE
Fuseki UI broken for "edit" tab when number of graphs is large

### ISSUE THREAD

**Issue by LorenzBuehmann** [apache/jena#2267]
### Version

4.10.0

### What happened?

Reported on mailing list: https://lists.apache.org/thread/zdtjtl3qlypl7d713z7bd1117kfjq149

The Fuseki UI is broken when we work on a large number of graphs and open the "edit" tab, see
![image](https://github.com/apache/jena/assets/976029/6cb32816-d752-4ba9-a8b6-9d88d7a2cdec)

You can reproduce it with

``` bash
for i in {1..100..1}; do echo "<http://example.org/s> <http://example.org/p> <http://example.org/o> <http://example.org/g$i> ." >> /tmp/data.nq; done
$JENA_HOME/bin/tdb2.tdbloader --loc /tmp/tdb2/debug /tmp/data.nq
$FUSEKI_HOME/fuseki-server --loc /tmp/tdb2/debug --port 3333 /ds
```

### Are you interested in making a pull request?

No

**Comment by kinow** [comment]
Ah, yo umean because of how the pagination component is being rendered, @LorenzBuehmann ? Should be easy to fix if that's the problem.

**Comment by LorenzBuehmann** [comment]
Yes, I mean there are page numbers missing for sure when having hundreds of graph - note, I do not use the "edit" tab at all in Fuseki. I just reported the issue. Not sure if that is the real problem of the mailing list thread - but they user said "was working before" - not that I know which version this statement refers to

**Comment by kinow** [comment]
I also don't use that page, unless when I want to test some quick changes in small graphs.

Will fix that pagination as that is definitely broken. Once that's fixed I will look at the ASF lists archive and reply to that thread. Thanks @LorenzBuehmann !

**Comment by kinow** [comment]
Synced code, updated IDE's (phew, that took a while), and reproduced with the example from issue description (thanks!).

**Comment by kinow** [comment]
Still need to write tests, but here's a preview.

![image](https://github.com/apache/jena/assets/304786/5964059d-cce7-48ff-a548-dc1031a17415)

![image](https://github.com/apache/jena/assets/304786/afc61b14-b8ea-4c14-9dd2-78fa4f4fffde)

![image](https://github.com/apache/jena/assets/304786/9a23c532-2dac-491f-8ac9-36c3cecc7f91)

And while navigating through the rest of the UI, I noticed when clicking on the Dataset size count button, in the information about the dataset, it also created a really long list of graphs and count of triples per graph.

![image](https://github.com/apache/jena/assets/304786/f4d570e8-bdbe-48e8-9d91-a556b6dbb573)

I will see whether we need/can add a scrollable area, or pagination here too (probably the latter, less surprise to users, more uniform...).

**Comment by kinow** [comment]
Added the same table to the info view now:

![image](https://github.com/apache/jena/assets/304786/08b07d81-57b5-4470-83d9-5773ad5d44ed)

![image](https://github.com/apache/jena/assets/304786/4171d8e9-2ab9-4941-90c4-2eca4913f0fd)

**Comment by kinow** [comment]
Now just missing the unit/e2e tests, to be completed next spare time window :crossed_swords: :muscle:
