### ISSUE TITLE
Migrate service-enhancer to caffeine

### ISSUE THREAD

**Issue by Aklakan** [apache/jena#2271]
### Change

The service enhancer module currently uses Guava Cache and should migrate to Caffeine.
This does not remove the need for Guava because its RangeMap / RangeSet data structures are still needed.

- [ ] A documentation update to https://jena.apache.org/documentation/query/service_enhancer.html is needed for how one can build the jar-bundle for use with Fuseki using the steps mentioned in https://github.com/apache/jena/issues/2161#issuecomment-1913180619

### Are you interested in contributing a pull request for this task?

Yes

**Comment by afs** [comment]
Completed by #2288.
