### ISSUE TITLE
Does Jena Fuseki support converting xsd:duration to days?

### ISSUE THREAD

**Issue by landong1973** [apache/jena#2272]
### Version

4.10.0

### Question

prefix xsd: <http://www.w3.org/2001/XMLSchema#>
select distinct *
where{
  bind("P10DT5H30M"^^xsd:duration as ?duration)
  bind (?duration/ xsd:dayTimeDuration("P1D") as ?durationInDays)

}

the SPARQL returns empty ?durationInDays , is there any workaround in Fuseki?

**Comment by afs** [comment]
@landong1973 - dividing duration is not currently supported. No reason it can be added, it just hasn't been done.

Contributions welcome!

Recorded as https://github.com/apache/jena/issues/2273

**Comment by flange-ipb** [comment]
There is [fn:days-from-duration](https://www.w3.org/TR/xpath-functions/#func-days-from-duration). So
```
PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT *
WHERE {
  BIND("P10DT5H30M"^^xsd:duration as ?duration)
  BIND(fn:days-from-duration(?duration) as ?durationInDays)
}
```
would give you the day component of the duration. A result with as decimal number would require an implementation of [op:divide-dayTimeDuration-by-dayTimeDuration](https://www.w3.org/TR/xpath-functions/#func-divide-dayTimeDuration-by-dayTimeDuration) as @asf already mentioned.

**Comment by landong1973** [comment]
Thank you both, the solution below works for me now. 

PREFIX fn: <http://www.w3.org/2005/xpath-functions#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT *
WHERE {
  BIND("P10DT5H30M"^^xsd:duration as ?duration)
  BIND(xsd:integer(fn:days-from-duration(?duration)) as ?durationInDays)
}
