### ISSUE TITLE
N3 support

### ISSUE THREAD

**Issue by josirosenfeld** [apache/jena#2283]
### Version

3.14.0

### Question

Is there N3 notation support in any version of Apache Jena?

**Comment by ajs6f** [comment]
In [Jena's IO documentation](https://jena.apache.org/documentation/io/) we find:

> .n3 is supported but only as a synonym for Turtle.

Does that help with your question?

**Comment by afs** [comment]
Maybe https://github.com/william-vw/jen3

**Comment by rvesse** [comment]
Worth noting that Jena 3.14.0 is from January 2014 and is 4 years old at this point.  The project is currently in the process of releasing Jena 5.0.0 (our first release candidate just came out last week).

You should really look at using recent versions of Jena as there are a number of [Security Advisories](https://jena.apache.org/about_jena/security-advisories.html) that impact old versions

**Comment by josirosenfeld** [comment]
> In [Jena's IO documentation](https://jena.apache.org/documentation/io/) we find:
> 
> > .n3 is supported but only as a synonym for Turtle.
> 
> Does that help with your question?

Thank you, I have seen this link before and according to it the N3 format is not supported. However, when I look at the Apache Jena source code there is a n3 subdirectory with N3JenaWriter.java for example, which gives me the sense that N3 may actually be supported.

**Comment by josirosenfeld** [comment]
> Maybe https://github.com/william-vw/jen3

Thank you, I have looked at this code and have had some issues getting all the tests to run and it's not compatible with the most up to date version of Apache Jena

**Comment by josirosenfeld** [comment]
> Worth noting that Jena 3.14.0 is from January 2020 and is 4 years old at this point. The project is currently in the process of releasing Jena 5.0.0 (our first release candidate just came out last week).
> 
> You should really look at using recent versions of Jena as there are a number of [Security Advisories](https://jena.apache.org/about_jena/security-advisories.html) that impact old versions

Thank you, yes. I only used that version because it was compatible with jen3

**Comment by josirosenfeld** [comment]
I see, it does answer my question. In other words, it doesn't actually
support N3 notation.

**Comment by ajs6f** [comment]
Great, glad we could help!
