### ISSUE TITLE
Service enhancer with fuseki as service 

### ISSUE THREAD

**Issue by royassis** [apache/jena#2303]
### Version

5.0.0-rc1

### Question

I am running fuskei as a service using the `./fuseki` executable (Which I copied to `/etc/init.d`).
Is it possible to use service enhancer with fuskei as a service instead of using the  `./fuseki-server` executable? 

I am getting:
`invalid URI scheme loop` When using this query:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meshep: <loop:bulk+5:http://172.31.39.52:8080/mesh/sparql>

select *
{
  SERVICE meshep:{
    SELECT * WHERE {
      ?m rdfs:label ?d
    }
    LIMIT 10
  }
}
```

I didn't have any issues when I run it using `./fuseki-server`

**Comment by afs** [comment]
`./fuseki-server` looks for `fuseki-server.jar` and failing that `jena-fuseki-server-*.jar` and add `.../extra/*`

The init script `fuseki` uses `fuseki-server.jar` to run Fuseki. An environment variable `FUSEKI_CLASSES` (details in the script) ius used to add classes.

Neither has the service enhancer by default. Are you adding classes when running `./fuseki-server` via `extra`?

**Comment by royassis** [comment]
Thanks @afs 
`FUSEKI_CLASSES` was what I was looking for. Now it works.
I did create run/extra and added the relevant .jar's.
