### ISSUE TITLE
oom issues with tdb2.tdbquery

### ISSUE THREAD

**Issue by royassis** [apache/jena#2308]
### Version

5.0.0-rc1

### What happened?

OOM error when querying a TDB2 database using tdb2.tdbquery cli. 
Size of database is 1.8G. 
This is the query:
```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>

SELECT ?node ?descriptorLabel (str(?Label) as ?value)
{
   ?node a ?class .
   ?node meshv:identifier ?nodeId .
   ?node ?descriptor ?Label .
   GRAPH <http://id.nlm.nih.gov/mesh/vocab>{
       ?class a owl:Class .
       ?descriptor a owl:DatatypeProperty .
       ?descriptor rdfs:label ?descriptorLabel .
   }
}
```
This is a link for downloading the data as .ttl format:
https://nlmpubs.nlm.nih.gov/projects/mesh/rdf/mesh.nt

### Are you interested in making a pull request?

No

**Comment by royassis** [comment]
I see this comment in `tdb2.tdbquery`:
`# JVM_ARGS : don't set here but it can be set in the environment.`

**Comment by rvesse** [comment]
Can you provide the stack trace you get please?

**Comment by royassis** [comment]
Hey @rvesse.
I do not have the stack trace at hand. 
What I did was to setup the `JVM_ARGS ` env variable with `-Xmx4096m` for increased heap size
