### ISSUE TITLE
ResultSetFactory don't close the InputStream.

### ISSUE THREAD

**Issue by wangxj3** [apache/jena#2309]
### Version

mian

### What happened?

ResultSetFactory don't close the InputStream. In the line of 69,function of load(String filenameOrURI, ResultsFormat format)

### Are you interested in making a pull request?

None

**Comment by rvesse** [comment]
Not a bug, this is by design. It allows for Jena to stream process the results which minimises memory overheads

Consumers of the ResultSet API are required to ensure they `close()` it appropriately which will close the underlying `InputStream` (or other resources) where appropriate

**Comment by afs** [comment]
If an InputStream is passed in, then the responsibility for closing is the caller, which fits the try-with-resources pattern.

In the case of `load(String filenameOrURI, ResultsFormat format)`, the `InputStream` is created within `ResultSetFactory` and should be used with try-with-resources.
