### ISSUE TITLE
Typo in org.apache.jena.sparql.serializer.FormatterElement

### ISSUE THREAD

**Issue by qmj0923** [apache/jena#2311]
### Version

4.10.0

### What happened?

I think the comparison should be `el.getElements().size() == 1` in the code snippet below.

https://github.com/apache/jena/blob/e54eb5e45fbb546342681046049509a76df58cc9/jena-arq/src/main/java/org/apache/jena/sparql/serializer/FormatterElement.java#L251-L255

Considering that `ElementUnion` always has at least two elements, this issue may not affect the correctness of the program.

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
@qmj0923 Thank you for the report.

As you say, SPARQL syntax does not allow a union with a single member. It might arise if a query syntax tree is constructed by code including Jena's algebra to syntax converter, `OpAsQuery`.

The code will drop through to the loop which does handle the case of union-of-one in the same way but an explicit test and handling is clearer.

PR #2314

**Comment by qmj0923** [comment]
Thank you for resolving the bug! Please close this issue once the fix is completed.
