### ISSUE TITLE
Add Tooltip Feature to Main Upload Bar

### ISSUE THREAD

**Issue by neumarcx** [apache/jena#2371]
### Version

latest

### Feature

in addition to the color coding and the upload bar a textual indicator in form of tooltip can be used to accompany the upload results. further improving readability. 

### Are you interested in contributing a solution yourself?

No

**Comment by kinow** [comment]
Agreed. If you have a long list of items, and just one or two fails, it can be hard to see the text in the current version.

Stealing your own image here, @neumarcx :grimacing: 

![image](https://github.com/apache/jena/assets/304786/bf2556f6-09f3-42e3-a955-510bdf18a7c0)

**Comment by kinow** [comment]
PR arriving in some minutes. We could use the fancy tooltip component provided by Bootstrap, but I think it would be an overkill as using `title="text"` here seems work fine. Tested on Chromium and FFox.

![image](https://github.com/apache/jena/assets/304786/a0590fc4-5e86-46de-8664-c03ceba07bf8)

**Comment by neumarcx** [comment]
yes this looks sufficient
