### ISSUE TITLE
LPBRuleEngine's usage of LinkedList for activeInterpreters is a hot spot

### ISSUE THREAD

**Issue by osi** [apache/jena#2382]
### Version

4.10

### What happened?

the `LPBRuleEngine` keeps track of active interpreters in a `LinkedList`. access to this list is synchronized. we have observed that this can be a hot spot with removals from the list taking some time. performance was greatly improved by using a `HashSet` instead

### Are you interested in making a pull request?

Yes

**Comment by afs** [comment]
This looks like a good idea.

**Comment by osi** [comment]
excellent! do you want me to prepare a PR, or is this a straightforward enough change that you want to make it directly?

**Comment by afs** [comment]
PR please!
