### ISSUE TITLE
Update the lexical space and value space of rdf:XMLLiteral to comply with RDF 1.1

### ISSUE THREAD

**Issue by afs** [apache/jena#2430]
### Version

3.17.0, 4.x.x, 5.0.0

### What happened?

Report: https://lists.apache.org/thread/ot70fzow1wzjxrnwgxdgylhjj1g5g5gr

### Are you interested in making a pull request?

Yes

**Comment by namedgraph** [comment]
The RDF/XML in the example is not canonical though?
