### ISSUE TITLE
`mvn clean install` fails

### ISSUE THREAD

**Issue by sszuev** [apache/jena#2465]
### Version

5.0.0

### Question

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/mvn/apache-maven-3.8.6
Java version: 17.0.6, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-17.0.6
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "6.5.0-28-generic", arch: "amd64", family: "unix"

last commit: cf3a14008b7cbcf5abc8cf485eec4501566f8469
```
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16:45 min
[INFO] Finished at: 2024-05-12T19:22:41+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jena-integration-tests: Could not resolve dependencies for project org.apache.jena:jena-integration-tests:jar:5.1.0-SNAPSHOT: org.apache.jena:jena-cmds:jar:tests:5.1.0-SNAPSHOT was not found in https://repository.apache.org/snapshots during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :jena-integration-tests

```
![image](https://github.com/apache/jena/assets/17473366/2f4b8fb2-21a9-47c7-919a-94b723220c70)

**Comment by kinow** [comment]
(just passing by to say I will try to reduce the total time for tests int he UI -- hadn't noticed it was taking so long)

**Comment by afs** [comment]
The UI tests don't take that long on my machine. 

The time is the whole step which includes downloading node and yarn which can be a bit variable in time taken.

**Comment by afs** [comment]
This happened elsewhere in the last few days for me as well. This maven issue should go away - somewhere a fetch of jena-cmds failed which get recorded in the local maven repo and it does not try again.

You can delete the local maven repo entry for jena-cmds:5.1.0-SNAPSHOT. Or manually delete "target/" and build locally with "install".

**Comment by afs** [comment]
Then it may be an upstream issue which we have very little control over.

There is a deployment build of Jena running at the moment (Monday, 07:52 UTC) which should reproduce all the snapshot artifacts.

https://ci-builds.apache.org/job/Jena/

(Your maven 3.8.6 is little behind but I doubt that is related)

I've successfully built Jena locally today.

**Comment by afs** [comment]
@sszuev has the problem resolved itself?

**Comment by afs** [comment]
Found the problem - jena-integration-test has an unnecessary dependency on jena-cmds tests. A recent POM change stopped producing that unnecessary artifact.

The apache-jena "Distribution" is from teh same POM change - no sources are being produced which isn't right.
