### ISSUE TITLE
OntModel enhancements

### ISSUE THREAD

**Issue by sszuev** [apache/jena#2487]
### Version

5.1.0

### Feature

There is some functionality that is present in the old model, but is missing in the new one
- methods `OntModel#writeAll`
- builtin annotation properties' accessors (e.g. for `owl:backwardCompatibleWith`). (for other builtin entities appropriate accessors could also be added, but I think it is better left as it is, because there are a lot of builtin entities)
- `OntTools` (do we need the analogue?)

Also, 
- `OntProperty#addSubProperty` is missed; 
- several TODO's 
- specialized `GraphRepository` for use with `GraphMaker`

### Are you interested in contributing a solution yourself?
yes

**Comment by afs** [comment]
Is this complete now #2487 has been merged?

(2487 didn't have the "resolves #2487" text that automatically closes an issue when a PR is merged)

**Comment by afs** [comment]
Ok - we can leave the issue open.

**Comment by sszuev** [comment]
all work on this task has been completed. can be closed

**Comment by afs** [comment]
🎆 🎉
