### ISSUE TITLE
Using a reasoner to retrieve individuals beloning to a Class

### ISSUE THREAD

**Issue by Demirrr** [apache/jena#2523]
### Version

5.0.0

### Question

Is it possible to use a reasoner to infer individuals beloning to an OWL Class Expression on a given RDF knowledge graph ?

**Comment by afs** [comment]
Hi @Demirrr -- 

Jena doesn't provide all of OWL reasoning. It has some ruleset for a subset. To go further, a complete OWL reasoner can be wired into Jena.

**Comment by Demirrr** [comment]
Dear @afs,

Thank you for your answer. 

Would it possible to infer such individuals by using the existing ruleset from the command line ?

**Comment by afs** [comment]
Hi - I don't use OWL or the inference and rule system (which by the way is datalog expressivity) to give an answer. Users of Jena inference can help, including how to configure an external OWL reasoner if that's necessary for the expressivity of the OWL Class Expression you want.

Good places to ask questions are the Jena users mailinglist ([users@jena.apache.org - you need to subscribe first](https://jena.apache.org/help_and_support/) or ask on StackOverflow, with tags "jena", "jena-rules", "reasoner".
