### ISSUE TITLE
`UNDEF` in `VALUES` doesn't work with `SERVICE`

### ISSUE THREAD

**Issue by mhoangvslev** [apache/jena#2556]
### Version

5.0.0

### What happened?

Given the query below:

```sparql
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT DISTINCT ?product ?label ?propertyTextual WHERE {
    VALUES ?bgp1 { <https://query.wikidata.org/sparql> UNDEF }
  	
    SERVICE ?bgp1 { 
  		?item wdt:P31 wd:Q146. # Must be a cat
	} 
}

```

Executing this query cause error: `Service URI not bound: ?bgp1`

According to the [spec](https://www.w3.org/TR/sparql11-query/#inline-data), using UNDEF should not raise an error:
> Data can be directly written in a graph pattern or added to a query using VALUES. VALUES provides inline data as a [solution sequence](https://www.w3.org/TR/sparql11-query/#defn_sparqlSolutionSequence) which are combined with the results of query evaluation by a [join](https://www.w3.org/TR/sparql11-query/#defn_algJoin) operation. It can be used by an application to provide specific requirements on query results and also by SPARQL query engine implementations that provide [federated query](https://www.w3.org/TR/sparql11-query/#basic-federated-query) through the SERVICE keyword to send a more constrained query to a remote query service.

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
See https://www.w3.org/TR/sparql11-federated-query/#variableService

Variables in the SERVICE clause are "best effort". `<https://query.wikidata.org/sparql>` makes sense but an unbound variable does indicate where to execute the SERVICE.

It has to be constrained somehow. What are you expecting? If you want it to ignore, then `SERVICE SILENT` may do what you want - it will generate a warning but otherwise  skip the execution of that step.

**Comment by mhoangvslev** [comment]
In my use-case, since the data in `VALUES` are retrieved from external process, there is no warranty that the variables would be bound eventually, i.e, having `UNDEF` as value. In this case yes, I expect the BGP under `SERVICE` to simply be ignored. That said, `SERVICE SILENT` is satisfactory enough, although its usage can cause important errors to get ignored, e.g. HTTP 300-500.

**Comment by afs** [comment]
All `SERVICE` execution goes through an extension point `ServiceExec.exec`.

One collection of extensions, focued on federated query performance, are:
https://jena.apache.org/documentation/query/service_enhancer.html

You can add your own policy via `ServiceExec.exec`.

**Comment by mhoangvslev** [comment]
Alright, many thanks for your prompt assistance ☺️
