### ISSUE TITLE
Allow custom serialization formats in Fuseki

### ISSUE THREAD

**Issue by Ostrzyciel** [apache/jena#2700]
### Version

dev (d9bf473)

### Feature

I wrote a custom serialization format for RDF, along with the writer, parser, and all the registration shenanigans ([source in Scala](https://github.com/Jelly-RDF/jelly-jvm/blob/effb9ead5fb34a4ca0feee5c0147e093ba7d70d3/jena/src/main/scala/eu/ostrzyciel/jelly/convert/jena/riot/JellyLanguage.scala#L61)). It works great when loading RDF files into Fuseki UI, or when using the RIOT CLI utility. The problem is, I can't get it to work over content negotiation in Fuseki with SPARQL CONSTRUCT queries or with the graph store protocol. Fuseki always ignores my Accept header with the custom content type and returns Turtle anyway. I dug a bit into the code and found this:

- [`ResponseDataset.doResponseDataset`](https://github.com/apache/jena/blob/d9bf473405b4242215c626126d01f9463a27ccb4/jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/servlets/ResponseDataset.java#L82) uses `DEF.constructOffer` as the list of accepted content types.
- [`DEF.constructOffer`](https://github.com/apache/jena/blob/d9bf473405b4242215c626126d01f9463a27ccb4/jena-fuseki2/jena-fuseki-core/src/main/java/org/apache/jena/fuseki/DEF.java#L35) is a public static final field, so it cannot be modified or extended in any way.

The `DEF` class also contains a few other lists of content types that serve similar purposes – they are also static final.

So, as I understand, there is currently no way of adding a new serialization format for Fuseki responses, besides forking the entire codebase or resorting to something like reflection (nooooo...).

Assuming this is correct, would it make sense to create some kind of a simple registration mechanism for supported content types in Fuseki, similar to [`RDFLanguages`](https://github.com/apache/jena/blob/d9bf473405b4242215c626126d01f9463a27ccb4/jena-arq/src/main/java/org/apache/jena/riot/RDFLanguages.java#L265) in RIOT?

### Are you interested in contributing a solution yourself?

Yes

**Comment by namedgraph** [comment]
Doesn't Fuseki support all languages from `RDFLanguages`?

**Comment by Ostrzyciel** [comment]
> Take a look at `ResponseOps.paramOutput()` method shown in your snippet, I believe there's a querystring/form `output` parameter you can supply with the short name of a registered format to force a specific output format overriding normal Conneg logic

Ah, thanks for pointing this out, I missed it completely. This helps.

But, AFAIK, this is a non-standard parameter in the SPARQL protocol, so content negotiation should still be supported, as it's more portable :)

**Comment by namedgraph** [comment]
> As far as I understand the code, it can serialize in any of the registered languages, but it does not support them all in content negotiation logic.

That's weird then. That's how I've implemented [conneg logic](https://github.com/AtomGraph/Core/blob/master/src/main/java/com/atomgraph/core/MediaTypes.java) using JAX-RS (or actually based on `RDFParserRegistry` and `RDFWriterRegistry`).

**Comment by afs** [comment]
Content negotiation is controlled by constants in `DEF. *Offer`. Currently these are final.

There shouldn't be any problem with making it extensible.

- Create (final) constants named `default...`
- Make the current versions non-final and set to the default for that constant.

**Comment by Ostrzyciel** [comment]
@afs I was actually thinking more in the direction of a registry system, like in `RDFLanguages`. Then plugins could register media types on runtime, without having to override any class. I want this to work also with unmodified Fuseki, just by dropping an additional JAR into the classpath.

**Comment by afs** [comment]
> override any class

It's only setting globals, not a class override. A registry of sorts. I'll do a PR.

The style here is to have defined set of possibilities at startup, doing as much parsing work as possible, and set the different options for the different response modes.

This is content negotiation and the client may request one of several possibilities which is more than a simple registry lookup of the `Accept` header. This is what `ConNeg.chooseContentType` does - finds the choice from the "accept" list and the "offer" list, including client-side `q=` ("quality").

If we are going to make it configurable, then there are other cases - for example, a system may not wish to support RDF/XML, or may wish to change the order of matching equal choices, or change the defaults (no `Accept` or `*/`).

You can build the configuration by inspecting registries if you want to. That's one way.
 
You can achieve that "drop-in jar" in two ways:

- General Jena - https://jena.apache.org/documentation/notes/system-initialization.html
- Fuseki modules - https://jena.apache.org/documentation/fuseki2/fuseki-modules.html

In both cases, you have to build the jar or classpath appropriately, e.g. the scale runtime.
