### ISSUE TITLE
Using JFlex Maven plugin in Jena-Iri

### ISSUE THREAD

**Issue by arne-bdt** [apache/jena#2732]
### Change

While trying to speed up parsing of RDF/XML, I profiled the parsing process.
It seems that resolving/parsing IRIs is one of the most time consuming parts in the whole process.
When trying to look into `org.apache.jena.iri.impl.LexerPath#yylex`,  I found hat the whole file has been" generated by JFlex 1.4.3 on 04/03/12".
Fortunately, JFlex is still actively developed and the latest release is JFex 1.9.1 from 2023-03-11.
`NotesAFS.txt` explains how to genereate the code with JFlex. But maybe no one has tried the process for 12 years now.
I don´t know if the "maven jflex plugin" was available in 2012 or if there is a reason, why JFlex has not been integrated in the build process,
Since Jena-Iri is a core part of the Apache Jena libraries, I think it may be wise to ensure, that the generated code is reproducable.

Would it be a good idea to integrate the "maven jflex plugin" instead of the manual process?

PS: I could not find any other Java IRI parser library, except for RDF4J.

### Are you interested in contributing a pull request for this task?

Perhaps?

**Comment by afs** [comment]
> While trying to speed up parsing of RDF/XML

Which parser?  RRX (SAX)?

> PS: I could not find any other Java IRI parser library, except for RDF4J.

This is my proposed replacement for `jena-iri`.

The big issue really is that the error messages will change. I hope uses find IRI3986 error messages somewhat less cryptic :-)

https://github.com/afs/x4ld/tree/main/iri4ld - specifically [IRI3986.java](https://github.com/afs/x4ld/blob/main/iri4ld/src/main/java/org/seaborne/rfc3986/IRI3986.java).

It does not depend on Jena except for its tests - it runs itself against jena-iri to check.

It parses/validates RFC 3986 syntax at the cost of a single java object allocation. It's only if the caller asks for parts of a IRI does it split the string.

Jena has `IRIx` as a plugin extension point. `iri4ld` is currently passing Jena's `IRIx` test suite and last time I checked

With the associated IRI3986 adapter for Jena, it worked the last time I tried in the Jena build. I haven't had time to get back to it and it missed Jena 5.0.

IRI3986 has URI scheme specific checking support as well, including DID's.

----

Background/general:

For several of the places where there is generated code, Jena ships the generated source code in several places so it can be built without having to setup tools chains. Things have got better over the years and maybe plugins now execute the tool and not depend on external setup.

> I don´t know if the "maven jflex plugin" was available in 2012 

The earliest version in maven central is 2014 :-)

**Comment by arne-bdt** [comment]
> Which parser? RRX (SAX)?

I copied rrx_stax_ev and rrx_stax_sr, which worked with both woodstox and aalto. Just two tiny fixes and all tests succeeded.
My benchmarks showed, that the "sr" variants were a bit faster, so I based my furhter work on that variant.

Only the changing error messages are preventing you from integrating the new code into Jena? 
Is there anyting I could do?

**Comment by afs** [comment]
"RRX SAX" is faster than "ev" and "sr" (using the JDK XML).  It's the wired in RDF/XML parser RDF/XML by default.

But I wouldn't have got to a SAX implementation without doing the easier EV! Converting to EV to SR was mechanical ... but wasn't really faster. (I've kept EV and SR alive - it's quite good discipline - 

> Only the changing error messages are preventing you from integrating the new code into Jena?

That and checking.

> Is there anything I could do?

I'm just coming to the end of implementing RDF 1.2/SPARQL 1.2 as it is today in the RDFstar WG (things will change more - that's the nature of Working Groups). 

I could provide a buildable IRI3986 extension using `JenaSubsystemLifecycle`.

Let's take it to dev@ about migration of IRI code. 

> Just two tiny fixes 
Interesting.

**Comment by arne-bdt** [comment]
Since Jena-Iri might be replaced by code that does not use Jflex, I close this issue.
