### ISSUE TITLE
how to debug LOADING_REMOTE_CONTEXT_FAILED problems?

### ISSUE THREAD

**Issue by VladimirAlexiev** [apache/jena#2739]
### Version

5.1.0

### Question

https://github.com/EKGF/dprod/issues/90:

Trying to convert https://github.com/EKGF/dprod/blob/main/examples/data-quality/example.json with riot causes error:
```
riot.bat -out=trig -syntax=jsonld example.json
There was a problem encountered loading a remote context [code=LOADING_REMOTE_CONTEXT_FAILED].
```
The context is https://ekgf.github.io/dprod/dprod.jsonld and:
- it's served as `content-type: application/ld+json` (reading through the JSONLD spec, I can't see whether it should be `json` or `ld+json` but all examples use `.jsonld` for the context URL)
- the certificate is valid
- example.json works ok on the JSONLD Playground: https://json-ld.org/playground/

So what may be the reason for the problem?
- https://stackoverflow.com/questions/41494678/how-can-i-override-the-context-when-loading-json-ld-in-jena correctly points out that the error is generic and may encompass a whole gamut of problems
- https://github.com/apache/jena/issues/1765 shows an extra reason, eg `message=Unexpected response code [403]` but that reason is not printed by `riot`
- https://github.com/apache/jena/commit/44b5535dc47b0159a74ff93e4d41e71e3c69c4ec says `removed the printStackTrace when "loading remote context failed"` but that's just in a test

**Comment by afs** [comment]
Getting `example.json` returns an HTML document; the github display of the file.
Use the "raw", the processing is all inside Titanium JSON-LD.

Internally, there is a nested stacktrace that says:

```
    A keyword [@context] redefinition has been detected.
```

My guess is that it is because of the array but I'm not a JSON-LD expert.

**Comment by VladimirAlexiev** [comment]
Thanks @afs !

The reason is context nested inside context (actually dprod.jsonld is not a context at all, it's a dumped ontology).
So the Playground is more lenient than Titanium (thus Riot). But really dprod.jsonld is to blame.

Thank for the PR you made!
I'll close this specific issue.

**Comment by afs** [comment]
Looks like https://github.com/filip26/titanium-json-ld/issues/348.
