### ISSUE TITLE
Possible bug with normalize of dtype in LiteralLabel

### ISSUE THREAD

**Issue by arne-bdt** [apache/jena#2741]
### Version

5.2.0-SNAPSHOT

### What happened?

By accident, I stumbled across two calls in  `org.apache.jena.graph.impl.LiteralLabel` to the static function `normalize` , which set a local variable `dtype`, which is not used afterwards.
But there is a class variable `this.dtype` which maybe should have been set to the result of `normalize` instead, otherwise normalize would have no effect at all.
![image](https://github.com/user-attachments/assets/371346f7-5189-42e1-a094-2672c1d92de8)

I tried to comment the two lines out but as expected the following tests were still sucessful:
- `org.apache.jena.graph.test.TestTypedLiterals`
- `org.apache.jena.graph.test.TestLiteralLabels`
- `org.apache.jena.graph.test.TestLiteralLabelSameValueAs`

Since I can´t find any example, showing what normalize should do, I don´t feel confident enough to add tests and provide an appropriate fix.

### Are you interested in making a pull request?

Maybe

**Comment by afs** [comment]
Probably should be `this.dtype` or better make the construct argument `datatype`.
It will impact line 167 if not done.

`normalize` chooses a derived datatype (e.g. xsd:int from xsd;Integer)
