### ISSUE TITLE
Blank node generated instead of named object when specifying a reverse property

### ISSUE THREAD

**Issue by rorlic** [apache/jena#2758]
### Version

4.7.0

### What happened?

When converting the attached JSON-LD file to N-triples a blank node is generated instead of a named node, that is, the object identity is not correctly recognized for a reverse property in this specific case.

### Steps to reproduce
1. Save the example [test.json](https://github.com/user-attachments/files/17260407/test.json) file locally
2. Run the following command:
```bash
riot --syntax=JSONLD --output=n-triples test.json
```

### Actual result
```
_:Bcf4b04cff5f6cb2cfbb33edc9e94515c <http://example.org#contains> <http://example.org/id/c1> .
_:Bcf4b04cff5f6cb2cfbb33edc9e94515c <http://example.org#parentId> "p1" .
<http://example.org/id/c1> <http://example.org#contains> <http://example.org/id/s2> .
```
> **Note** that the blank node name will be different than above (by design).

### Expected result
Instead of the blank node a named node `<http://example.org/id/p1>` is generated similar as when executed in [JSON-LD playground](https://json-ld.org/playground/):
```
<http://example.org/id/c1> <http://example.org#contains> <http://example.org/id/s2> .
<http://example.org/id/p1> <http://example.org#contains> <http://example.org/id/c1> .
```

### Are you interested in making a pull request?

None

**Comment by afs** [comment]
Jena 5.10 gives:

```
<http://example.org/id/c1> <http://example.org#contains> <http://example.org/id/s2> .
<http://example.org/id/p1> <http://example.org#contains> <http://example.org/id/c1> .
```

Jena5 uses [Titanium JsonLD](https://github.com/filip26/titanium-json-ld) for `--syntax=JSONLD` and it is JSON-LD 1.1.
Jena4 used [json-ld](https://github.com/jsonld-java/jsonld-java) which is JSON-LD 1.0.
