### ISSUE TITLE
Unneeded HashMap allocations in ValidationState

### ISSUE THREAD

**Issue by Ostrzyciel** [apache/jena#2797]
### Change

While profiling a piece of RDF parser code, I've noticed a whole lot of `HashMap` allocations on the heap – not HashMap entries – HashMaps. What could possibly be allocating tons of maps during RDF parsing?

It turns out to be the `ValidationState` class, an instance of which is allocated for each time we parse a datatype literal. It has these two fields: https://github.com/apache/jena/blob/04f377d8aefc0cb8faeb62022d402ef17a6e6e96/jena-core/src/main/java/org/apache/jena/ext/xerces/impl/validation/ValidationState.java#L53-L55

I find the note slightly funny.

The whole ID table tables thing is used only by `IDDV` and `IDREFDV` classes. I had to consult the RDF spec, because I didn't even know that such datatypes existed. It this XML thing: https://www.w3.org/TR/xmlschema11-2/#ID I think it's a very rarely used feature of RDF that certainly doesn't warrant allocating two hashmaps per literal.

Also: will the ID and IDREF validation even work if we allocate a new object for each literal parse? Then these hashmaps are not carried over... Did this even work?

## Solution

I'm submitting a PR that sets these hashmap fields to null by default, and only initializes them if needed (lazy initialization). Note that I'm not convinced that the ID/IDREF feature even works currently, but removing this outright would be a breaking change.

## Broader issue – for a separate thread

*(I will create a new issue with this, I'm leaving this here for context for now)*

Another thing is that I'm not convinced that we need to allocate a new `ValidationState` every time we parse a datatyped literal: 

https://github.com/apache/jena/blob/04f377d8aefc0cb8faeb62022d402ef17a6e6e96/jena-core/src/main/java/org/apache/jena/datatypes/xsd/XSDDatatype.java#L267-L272

This is a pretty heavy object to be allocating so often.

Many methods in ValidationState are unused, and there is a bunch of other dead code around it copied over from xerces, like the whole `ValidationManager` class. Removing this, however, would be a breaking change, so it's not in the scope of this issue.

### Are you interested in contributing a pull request for this task?

Yes

**Comment by Ostrzyciel** [comment]
Ooops, sorry, I just read the RDF spec more carefully:

> The other built-in XML Schema datatypes are unsuitable for various reasons and SHOULD NOT be used:
> -    [xsd:ID](https://www.w3.org/TR/xmlschema11-2/#ID) and [xsd:IDREF](https://www.w3.org/TR/xmlschema11-2/#IDREF) are for cross references within an XML document.

https://www.w3.org/TR/rdf11-concepts/#datatype-iris

Can we then just remove this feature entirely?

**Comment by arne-bdt** [comment]
Thank you for bringing this up! It looks like it could really use a cleanup...
