### ISSUE TITLE
Fuseki UI should not use absolute paths to load resources

### ISSUE THREAD

**Issue by ebner** [apache/jena#2889]
### Version

5.2.0

### Question

The file `webapp/index.html` references all resources using absolute paths, which prevents the use of the UI through a reverse proxy at a different path.

Let's assume that the UI is supposed to be served by a reverse proxy at the address `https://<host>/fuseki/`. All requests against `/fuseki/*` are proxied to `http://localhost:3030` which is a container serving Fuseki. The `index.html` references `./static/index-DRoCyVBH.js` and `./static/index-d9omhX6e.css`, which resolve into `https://<host>/static/index-DRoCyVBH.js` and `https://<host>/static/index-d9omhX6e.css`, respectively.

If the index file just omitted `./` in the beginning of the src/href then everything would be loaded relative to the path of the index file.

Is there anything that speaks against such a change?

**Comment by afs** [comment]
I'm a bit about what is happening.

Isn't `./...` being resolved in the browser? Or is Vue getting in the way?

**Comment by afs** [comment]
@ebner Glad to hear your system is now working!
